### ISSUE TITLE
安装Theos出错

### ISSUE THREAD

**Issue by prettymao** [buginux/WeChatRedEnvelop#10]
我是这步出错了
sudo /opt/theos/bin/bootstrap.sh substrate
提示
sudo: /opt/theos/bin/bootstrap.sh: command not found
我确实找不到这个bootstrap.sh文件啊。。。这个步骤是必须的吗？

**Comment by buginux** [comment]
根据我的推测，你应该是跳过了某个步骤，我觉得可能是：
1. 没有执行 `EXPORT THEOS=/opt/theos`
2. 没有将 theos clone 到 THESO 目录
你可以再重新确认下。

**Comment by zajsky** [comment]
新版的theos貌似真没有bootstrap.sh  ，
这里有个修改版有git://github.com/rpetrich/theos.git，另外教程里还可以从设备里提取dylib

**Comment by ArthurKli** [comment]
@zajsky @prettymao 上面修改版可以用，但是还是会提示少一个文件 需要拷贝出来：
`scp -P 22 root@192.168.0.103:/Library/Frameworks/CydiaSubstrate.framework/Headers/CydiaSubstrate.h $THEOS/include/substrate.h`

**Comment by buginux** [comment]
最新版的 theos 已经没有这个脚本了，可以跳过这步，直接执行后面的操作就可以了。
可以参见我更新过的博客：http://www.swiftyper.com/2016/01/25/ios-tweak-install-guide/

**Comment by youxigit** [comment]
==> Error: /Applications/Xcode.app/Contents/Developer/usr/bin/make package requires dpkg-deb.
make: *** [internal-package-check] Error 1

**Comment by buginux** [comment]
@youxigit 这个是没有安装 dpkg-deb 的错误。
