### ISSUE TITLE
现在功能没效果啊

### ISSUE THREAD

**Issue by x122536638** [buginux/WeChatRedEnvelop#100]
我把百度盘里的.app 转换成ipa 安装在越狱手机上  界面上有抢红包,但是实际没效果

**Comment by buginux** [comment]
你这种情况就很奇怪了，正常界面上显示了就已经抢成功了，你可以再确认一遍吧。而且我这里是没有问题的。

**Comment by x122536638** [comment]
微信 6.5.4 版本：链接: https://pan.baidu.com/s/1kUH8njD 我把这个WeChat下载下来,执行xcrun -sdk iphoneos PackageApplication -v WeChat.app  -o ~/Desktop/WeChat.ipa,然后安装这个ipa   没效果

**Comment by buginux** [comment]
你没做重签名吗

**Comment by x122536638** [comment]
没有

**Comment by x122536638** [comment]
我是安装在越狱的手机上的

**Comment by buginux** [comment]
越狱的可以直接去 cydia 下载。如果你要自己做签名就去看我的博客说明吧。

**Comment by x122536638** [comment]
appstore下载的包  然后装了你的cydia源 没效果啊,是不是因为我手机是10.1的?

**Comment by x122536638** [comment]
是因为我的账号没绑定银行卡....

**Comment by buginux** [comment]
👍 请给我打一笔精神损失费过来~
