### ISSUE TITLE
开发问题

### ISSUE THREAD

**Issue by x122536638** [buginux/WeChatRedEnvelop#102]
我按照http://blog.csdn.net/heiby/article/details/51792151研究走到 make package install总是报错
Tweak.xm:2: error: %orig does not make sense outside a method.网上没有答案.很难受

**Comment by buginux** [comment]
应该是你的 Tweak.xm 里面写错了，你自己再确认下。

**Comment by x122536638** [comment]
必须用xcode7吗  我现在是xcode8

**Comment by buginux** [comment]
这个无所谓的

2017年2月22日 +0800 PM1:14 x122536638 <notifications@github.com>，写道：

**Comment by wsihduog** [comment]
怎样只留抢红包开关项

**Comment by buginux** [comment]
跟开关没关系啊，你把其它都关掉不就好了。实在不行的话代码都在那里，你可以自己改。

**Comment by wsihduog** [comment]
我已全部改好
