### ISSUE TITLE
新版微信检测盗版

### ISSUE THREAD

**Issue by xly1208** [buginux/WeChatRedEnvelop#103]
目前，在最新版的微信6.5.5上重签名后会被检测出盗版应用。代码众多，不知道是怎么检测的。寻思hook一下bundleIdentifier吧，全局hook会导致应用打不开！不知新版是怎么检测的？有没有应对思路？

**Comment by buginux** [comment]
新版的代码没这个问题了

**Comment by xly1208** [comment]
@buginux  不是啊， 就是只重新签名，然后什么都不改的话，tweak代码不加，还是能检测到。估计是获取bundleIdentifier了，不过hook修改之后不能运行

**Comment by xly1208** [comment]
哈，懂你意思了，昨个刚更新了代码，我研究研究去哈！3Q大神

**Comment by xly1208** [comment]
看了一下你的代码，发现个问题！你现在的版本是一个安装在越狱设备的tweak。如果搞成非越狱版本的，签名后bundleIdentifier就变了，这样还是会检测到使用的是非官方版本，不知道这个问题该怎么解决

**Comment by buginux** [comment]
如果是检测 bundleid 的话，暂时我也没办法解决。这个待我再学习探究下吧。

**Comment by xly1208** [comment]
好吧，我也在研究这个，新版的检测这东西了，不过老版本的目测没有检测
