### ISSUE TITLE
2.0版本不会抢自己发的红包了？

### ISSUE THREAD

**Issue by lkmvip** [buginux/WeChatRedEnvelop#104]
2.0版本不会抢自己发的红包了？

**Comment by CainRun** [comment]
你这个是私发还是群聊发的?

**Comment by lkmvip** [comment]
自己发群聊里面的，以前会抢现在不会了，1小时前装了2.0测试了抢红包，刚才被封。

已换回老版本

**Comment by lkmvip** [comment]
ios9.3.3 微信6.5.5

**Comment by CainRun** [comment]
那这个得去问问作者了, 我还是6.5.3, 新版本还没弄

**Comment by buginux** [comment]
抢自己的现在放到设置里面了，可以自己设置开关，你更新下代码。

被封的话，是重签名版本的吗？如果是单纯抢红包的话，我从昨天测试到刚刚都还正常使用，没毛病。

**Comment by lkmvip** [comment]
ok我试试
