### ISSUE TITLE
您好问一下开发相关的问题

### ISSUE THREAD

**Issue by tata9898** [buginux/WeChatRedEnvelop#106]
@interface NewQRCodeScanner: NSObject

- (id)initWithDelegate:(id)arg1 CodeType:(int)arg2;
    ScanQRCodeLogicController *scanQRCodeLogic = [[objc_getClass("ScanQRCodeLogicController") alloc] initWithViewController:self CodeType:3];
 问一下 CodeType:(int)arg2; 这个值得意义是什么 而且我也注意到在6.3.16 和6.1 版本微信中
- (void)notifyResult:(id)arg1; 没有另外两个返回值
我去掉之后再6.3.16版本微信上没有问题 可是在6.1版本微信上就会闪退。。

**Comment by buginux** [comment]
这个主要是跟扫码有关的，CodeType 应该主要是条码、二维码或者其它码的类型。这里主要用来扫二维码，我没有深究它的流程，只是直接拿来用了。

版本不同的话，微信代码应该也是有差异的，所以出问题也很正常。

**Comment by tata9898** [comment]
scanQRCodeLogic.fromScene = 2; 这个的意思是啥啊

**Comment by hehe520** [comment]
buginux，你这么改了之后有没有出现非法客户端的警告
