### ISSUE TITLE
走到第二步，缺少tweek.mk文件

### ISSUE THREAD

**Issue by Homosum** [buginux/WeChatRedEnvelop#107]
WeChatRedEnvelop Homosum$ make
Makefile:6: theos/makefiles/common.mk: No such file or directory
Makefile:14: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.
WeChatRedEnvelop Homosum$

**Comment by buginux** [comment]
这个是找不到 theos 环境，你先执行 export THEOS=/opt/theos

**Comment by gank0326** [comment]
执行了export THEOS=/opt/theos 也是同样的报错

**Comment by gank0326** [comment]
搞定了，路径不对export THEOS=/Users/gank/theos ，指向安装的地方就可以了

**Comment by buginux** [comment]
这是你 ldid 的问题，应该是新版没签名的问题，直接使用 `brew install ldid` 试试。

**Comment by zhaofeiyue** [comment]
这个源码 在xcode 上能运行吗

**Comment by KintanTsia** [comment]
oceanomacminideMac-mini:WeChatRedEnvelop-master kintan$ make
grep: /Users/kintan/Desktop/OceanoApp 2017-02-09: No such file or directory
grep: /Users/kintan/Desktop/OceanoApp 2017-02-09: No such file or directory
grep: /Users/kintan/Desktop/OceanoApp 2017-02-09: No such file or directory
/tmp/theos/makefiles/rules.mk:39: warning: overriding commands for target `/Users/kintan/Desktop/OceanoApp'
/tmp/theos/makefiles/master/rules.mk:77: warning: ignoring old commands for target `/Users/kintan/Desktop/OceanoApp'
/tmp/theos/makefiles/rules.mk:39: warning: overriding commands for target `2017-02-09'
/tmp/theos/makefiles/master/rules.mk:77: warning: ignoring old commands for target `2017-02-09'
/tmp/theos/makefiles/rules.mk:42: warning: overriding commands for target `/Users/kintan/Desktop/OceanoApp'
/tmp/theos/makefiles/rules.mk:39: warning: ignoring old commands for target `/Users/kintan/Desktop/OceanoApp'
/tmp/theos/makefiles/rules.mk:42: warning: overriding commands for target `2017-02-09'
/tmp/theos/makefiles/rules.mk:39: warning: ignoring old commands for target `2017-02-09'
/tmp/theos/makefiles/rules.mk:45: warning: overriding commands for target `/Users/kintan/Desktop/OceanoApp'
/tmp/theos/makefiles/rules.mk:42: warning: ignoring old commands for target `/Users/kintan/Desktop/OceanoApp'
/tmp/theos/makefiles/rules.mk:45: warning: overriding commands for target `2017-02-09'
/tmp/theos/makefiles/rules.mk:42: warning: ignoring old commands for target `2017-02-09'
make: Circular /Users/kintan/Desktop/OceanoApp <- /Users/kintan/Desktop/OceanoApp dependency dropped.
make: Circular 2017-02-09 <- /Users/kintan/Desktop/OceanoApp dependency dropped.
make: Circular 2017-02-09 <- 2017-02-09 dependency dropped.
make: Circular 2017-02-09 <- /Users/kintan/Desktop/OceanoApp dependency dropped.
make: Circular 2017-02-09 <- 2017-02-09 dependency dropped.
make: Circular /Users/kintan/Desktop/OceanoApp <- /Users/kintan/Desktop/OceanoApp dependency dropped.
mkdir: /Users/kintan/Desktop/OceanoApp: Not a directory
mkdir: 2017-02-09: Not a directory
make: *** [17-46-27/未命名文件夹/WeChatRedEnvelop-master/.theos/build_session] Error 1

这个是怎么回事呢？试了一天都不行

**Comment by buginux** [comment]
环境有问题吧

**Comment by magicer0126** [comment]
是路径问题 在终端执行 vim ~/.bash_profile  在文件中添加 export THEOS=/opt/theos 和 export PATH=/opt/theos/bin/:$PATH 保存退出 然后再运行 source ~/.bash_profile 命令 再进入你工程目录 make 试试
