### ISSUE TITLE
朋友圈被封了  挺严重的 微信能检测出多开

### ISSUE THREAD

**Issue by 15041397127** [buginux/WeChatRedEnvelop#108]

**Comment by buginux** [comment]
多开的话，最近微信抢得比较严，这个暂时也没办法解决，只好尽量先不用了。

**Comment by fanyuecheng911006** [comment]
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @executable_path/libautoGetRedEnv.dylib | Referenced from: /var/containers/Bundle/Application/4A863705-1823-4B56-B8AD-090755D3B3FE/WeChat.app/WeChat | Reason: image not found
Triggered by Thread:  0
打开就闪退，不知道哪里有问题，我是新手。。。

**Comment by buginux** [comment]
这是你动态库注入的问题，可执行文件加载不到你的动态库了。

**Comment by gank0326** [comment]
可以给个你的wechat.app 让我自己签名试试吗？

**Comment by gank0326** [comment]
如果我bundle id 就用微信的，然后只安装这个，微信是不是就检测不出来了？

**Comment by buginux** [comment]
@gank0326 是没办法使用微信的 bundle id 的。

**Comment by xly1208** [comment]
@buginux 我现在在想一个办法，可以在微信启动时第一个ViewController里面hook修改bundleIdentifier，但是还是有点问题，你可以试试这种思路

**Comment by buginux** [comment]
@xly1208 👍 不如你试试看，然后来看看结果？

**Comment by xly1208** [comment]
@buginux   嗯，刚学习了一周，好多工具不熟呢，都是趁工作不忙的时候偷偷弄点。

**Comment by sxyclint** [comment]
正常啊
除了BundleID，还有其他参数供检测，具体见ManualAuthAesReqData
另外只hook了上面那个类里面的值对朋友圈也是会被检测到的，因为朋友圈和消息不完全是同一套检测逻辑

**Comment by hehe520** [comment]
buginux，微信会调用[KSSystemInfo systemInfo] 上传，bundleis, uuid，目前我已经确定绕过了多开检测，但是还有个非法客户端检测的警告没绕过， KSSystemInfo， WtloginPlatformInfo，SafeDeviceData 这三个是安全检测的类

**Comment by hehe520** [comment]
@buginux 微信会调用[KSSystemInfo systemInfo] 上传，bundleis, uuid，目前我已经确定绕过了多开检测，但是还有个非法客户端检测的警告没绕过， KSSystemInfo， WtloginPlatformInfo，SafeDeviceData 这三个是安全检测的类，你有没有收到过微信的非法客户端检测

**Comment by buginux** [comment]
@hehe520 暂时还没碰到呢。非法检测的还没有去研究过，等有空了再来仔细看看你提的这几个类。

**Comment by 15041397127** [comment]
收到过非法客户端检测这个警告

**Comment by xly1208** [comment]
@hehe520   你是怎么绕过多开检测的

**Comment by hehe520** [comment]
@xly1208  微信一启动会调用[KSSystemInfo systemInfo]，获取系统信息，里面有个openuuid 生成的uuid，随便改个不一样的，再去登录微信，他会提示你在新设备上登录，要短信验证了

**Comment by xly1208** [comment]
@hehe520 明白！我的思路是在APP启动的时候，在较早的时机hook其中的方法，修改bundleIdentifier和UUID。目前测试在application:didfinishLaunchingWithOption等这些类型的方法修改的话都会导致应用打不开。不知道你有没有啥思路

**Comment by hehe520** [comment]
@xly1208  微信在这3个类（KSSystemInfo， WtloginPlatformInfo，SafeDeviceData ）里都获取了bundle id，hook 带有bundleid 的方法，改成 com.tencent.xin 传回去就好

**Comment by xly1208** [comment]
@hehe520   主要是怕也在其他地方检测了，所以寻思越早hook越好！不过一直没找到合适的点

**Comment by AirSars** [comment]
证书用com.tencent.*

**Comment by oschanger** [comment]
Tweak不改客户端文件，一般不会被封吧？多开的话，改一下BundleID应该可以，但是还没看他其他的检测方法

**Comment by sunShuShu** [comment]
@xly1208 试没试过在构造函数里hook，这时候main函数还没开始执行，应该够早了

**Comment by xly1208** [comment]
@sunShuShu  不行，hook的点太早了无法运行，感觉它会做一些初始化的操作，所以不能太早，也不能太晚，找这个点不容易啊

**Comment by zjjno** [comment]
楼上的大兄弟 你都能想到用com.tencent.*你就想不到用*的吗
我一直是用*的描述文件重签名 绕过各种bundle id校验 分享给各位

**Comment by madage** [comment]
@zjjno  用*也没法绕过微信后台校验吧，bundle id 是发送到微信后台的，

**Comment by madage** [comment]
最近弄多开，发现了一些改机软件，就是不知道原理是什么，不知道大神知道原理么，希望普及一下

**Comment by xylinuxkernel** [comment]
想问一下，越狱后的应用能使用和官方微信一样的bundleid吗？

**Comment by buginux** [comment]
@xylinuxkernel 可以的
