### ISSUE TITLE
iOS10.2.1 重新签名问题

### ISSUE THREAD

**Issue by huanglins** [buginux/WeChatRedEnvelop#109]
用iOS App Signer签名完成后，通过Xcode安装提示了这个错误:
The entitlements specified in your application’s Code Signing Entitlements file are invalid, not permitted, or do not match those specified in your provisioning profile. (0xE8008016).

**Comment by buginux** [comment]
这是你证书的问题。

**Comment by huanglins** [comment]
之前用这个证书都能成功安装的，不知道是什么原因。

**Comment by huanglins** [comment]
谢谢，已经解决。  然而我重新再签一次就好。2333

**Comment by gank0326** [comment]
@huanglins  可以借你的包给我签名试下吗？
