### ISSUE TITLE
没有效果 T_T

### ISSUE THREAD

**Issue by 0ldRoger** [buginux/WeChatRedEnvelop#11]
微信版本: 6.3.13
机型版本: iPodTouch5 iOS7.1.2
在机子上编译的,编译成功安装成功,测试无效果
@buginux 求测试通过的微信版本

**Comment by xlh2046** [comment]
我也是测试没有效果
Cydia上提示：
This tweak can't make you rich!

**Comment by xlh2046** [comment]
今天再次测试
微信版本: 6.3.13
机型版本: iPad 4 iOS8.2
测试无效果

**Comment by buginux** [comment]
不好意思，最近比较忙，我会尽快确定问题的。

**Comment by buginux** [comment]
现在如何了，可以使用了么？

**Comment by zyfu0000** [comment]
依旧无法使用。。 
微信版本 6.3.16
机型版本: iPhone 6 iOS 9.0.2

**Comment by chenzhijie** [comment]
微信版本6.2.6

**Comment by chenzhijie** [comment]
微信版本6.2.6
手机iPhone5 iOS8.1.3
也是没效果

**Comment by buginux** [comment]
唔，我目前的手机版本是 8.2，微信版本是 6.3.16，可以正常使用。

**Comment by renzifeng** [comment]
安装上没有效果，不自动抢红包。
微信版本6.5.2
手机iPhone6P iOS 10.1

**Comment by buginux** [comment]
@renzifeng 确认下设置里面打开了没有

**Comment by renzifeng** [comment]
已解决，是自己改源码改出bug了，谢谢。
