### ISSUE TITLE
卡在第二步，能不能直接给个dylib

### ISSUE THREAD

**Issue by gank0326** [buginux/WeChatRedEnvelop#110]
src/WBBaseViewController.m:11:9: fatal error: 'objc/objc-runtime.h' file not found
#import <objc/objc-runtime.h>

**Comment by buginux** [comment]
你是不是 Xcode 开发环境没装好。

**Comment by gank0326** [comment]
我是先报找不到文件夹，然后看了你回复别人的issue  ，先执行 export THEOS=/opt/theos
执行完了还是不行，我就搜了下配置theos 环境，配置好了就报上面的错！所以我不知道应该怎么弄了，打算明天接着弄下。需要配置theos 环境吗？有没有什么操作步骤？

**Comment by buginux** [comment]
你的 Xcode Command Line Tool  有装好吗，如果没装好就先装这个。

Theos 的话，可以参考下我这个教程咯：http://www.swiftyper.com/2016/01/25/ios-tweak-install-guide/

**Comment by gank0326** [comment]
搞定了！感谢！！卡在第二步的朋友请参考http://blog.csdn.net/app_ios/article/details/52596230
