### ISSUE TITLE
今天突然闪退，是啥情况呢。没有升级微信。之前用的好好的

### ISSUE THREAD

**Issue by linovo** [buginux/WeChatRedEnvelop#111]
今天突然闪退，是啥情况呢。没有升级微信。之前用的好好的

**Comment by gank0326** [comment]
你第二步可以？theos环境怎么配的，有教程吗？

**Comment by gank0326** [comment]
可以给个你的wechat.app 让我自己签名试试吗？

**Comment by linovo** [comment]
@gank0326 我用的是上次作者提供的砸过壳的版本。你问下作者要吧

**Comment by gank0326** [comment]
@linovo 好吧 大神估计在忙，我搞了一下午各种报错，看来得重头开始学

**Comment by buginux** [comment]
链接: https://pan.baidu.com/s/1c2zN40g 密码: vne2 
这个就是上面讲的那个版本，你可以试试

**Comment by buginux** [comment]
@linovo 闪退的话，是偶然还是必崩？如果是必崩的话，应该是微信那边做了什么处理吧。

**Comment by linovo** [comment]
@buginux 必崩，打开就闪了。好像中午的是突然出现的。上午还好好的

**Comment by linovo** [comment]
@buginux 意思是说启动微信的时候服务端做了判断什么之类的？条件不符的话应用就被退出？

**Comment by buginux** [comment]
有这种可能，我现在暂时使用的是越狱的机子。所以这个问题我也不是很清楚，你可以试试看重新打包下。

**Comment by gank0326** [comment]
@buginux  多谢

**Comment by linovo** [comment]
苦于我机子现在是10.2没法越狱，不然就越了。那只能重新打包一个试试了。

**Comment by buginux** [comment]
10.2 已经有越狱了，参考下这个链接：http://yalujailbreak.com/

**Comment by linovo** [comment]
@buginux 然后支持的设备列表里边 并没有7P 囧

**Comment by buginux** [comment]
👍 除了 7p 全都支持，你可以买彩票了

**Comment by linovo** [comment]
@buginux 哈哈，这就尴尬了。还是感谢了。 今晚回去重新打包一个试试，闪退之后害得我聊天记录都没法备份

**Comment by huanglins** [comment]
确实闪退
