### ISSUE TITLE
最后一步错误

### ISSUE THREAD

**Issue by gank0326** [buginux/WeChatRedEnvelop#113]
执行最后一步，报错找不到路径，是因为这个executable_path 需要配置吗？

gank:Desktop ganshunwei$ /path/to/optool install -c load -p "@executable_path/WeChatRedEnvelop.dylib" -t wechat/Payload/WeChat.app/WeChat
-bash: /path/to/optool: No such file or directory

**Comment by buginux** [comment]
你在别的地方提过了，我就看得到的，就不要再重复开 issue 了，到时会很混乱的。
