### ISSUE TITLE
6.5.5 最新版的使用会闪退

### ISSUE THREAD

**Issue by huanglins** [buginux/WeChatRedEnvelop#114]
6.5.5以下版本的可以使用

**Comment by gank0326** [comment]
@huanglins  可以发我一个可用的去壳的？我的闪退应该也是用了6.5.5的微信

**Comment by huanglins** [comment]
pp助手可以直接下的


发自网易邮箱大师
在2017年03月02日 18:18，gank0326 写道：

@huanglins 可以发我一个可用的去壳的？我的闪退应该也是用了6.5.5的微信

**Comment by gank0326** [comment]
pp助手下载不了，我去别的网下个吧

**Comment by huanglins** [comment]
我直接在pp助手的mac 客户端下载的


发自网易邮箱大师
在2017年03月02日 18:20，gank0326 写道：

pp助手下载不了，我去别的网下个吧

**Comment by gank0326** [comment]
@huanglins 哎，换了N个包还是闪退，可能我中间哪个步骤搞错了😭！可以发个你的给我试试？373949629@qq.com,谢谢
