### ISSUE TITLE
No matching processes were found

### ISSUE THREAD

**Issue by ArthurKli** [buginux/WeChatRedEnvelop#12]
@buginux 安装后还是出现问题：

`Installing...
root@192.168.0.103's password: 
Selecting previously deselected package com.swiftyper.wechatredenvelop.
(Reading database ... 6908 files and directories currently installed.)
Unpacking com.swiftyper.wechatredenvelop (from /tmp/_theos_install.deb) ...
Setting up com.swiftyper.wechatredenvelop (0.0.1-1) ...
install.exec "killall -9 WeChat"
root@192.168.0.103's password: 
No matching processes were found
make: *** [after-install] Error 1
`
看起来像是找不到微信的进程？
虽然在ipad的Cydia已经能够看到WeChatRedEnvelop了  但是微信无法自动抢红包。

型号：iPad air
系统：IOS 7.0.6

**Comment by ArthurKli** [comment]
是因为我只安装了command line tools但是没有安装xcode的原因吧？

**Comment by ArthurKli** [comment]
我查了下ipad上面微信的进程名是“MicroMessenger”才对。改过来后正常make install且没有错误。
但是kill的意义是什么呢  好像还是抢不了红包。。。。

**Comment by buginux** [comment]
你的微信版本是最新版么？

**Comment by ArthurKli** [comment]
@buginux  不是 是6.1.1版本的。
貌似微信又改逻辑了：_如果账户已经被封但是又能抢到红包，会直接退出要求重新登录_
真是哔了狗了

**Comment by buginux** [comment]
可以尝试更新一下微信版本试试看。

**Comment by shuijinliuxi** [comment]
Unpacking replacement com.swiftyper.wechatredenvelop ...
Setting up com.swiftyper.wechatredenvelop (0.0.1-5+debug) ...
install.exec "killall -9 WeChat"
root@192.168.1.85's password: 
No matching processes were found
make: *** [after-install] Error 1

我也是这个问题……

**Comment by shuijinliuxi** [comment]
微信已经是最新版的了

**Comment by buginux** [comment]
No matching processes were found
make: *** [after-install] Error 1

**Comment by shuijinliuxi** [comment]
嗯，没看到要保持微信运行。刚刚试了下，可以了，tks
