### ISSUE TITLE
可以弄个微信技术交流的群吗

### ISSUE THREAD

**Issue by AirSars** [buginux/WeChatRedEnvelop#122]
如题，共同hook反编译研究过微信的群。技术类的，谁来建一个吧，可以一起研究研究微信是怎么检测的，有好的想法和功能也可以一起研究的做出来

**Comment by HomlesZhao** [comment]
亲，你来做吧😝

**Comment by kensla** [comment]
加我V信一起交流啊

**Comment by buginux** [comment]
建了个扣扣群，大家可以加进来一下

群里只交流技术，如果单纯只是有问题直接在这里提 issue 就行了，就尽量不要加群了

群号：538888537
