### ISSUE TITLE
所有步骤都成功了，打开后看不到微信小助手界面。

### ISSUE THREAD

**Issue by githhhh** [buginux/WeChatRedEnvelop#126]
依赖库都注入了，成功签名，安装。 打开后没有生效。从pp 助手下的6.5.5 版。

**Comment by buginux** [comment]
确定成功了吗，没出现的原因大多就是没成功

**Comment by githhhh** [comment]
成功了，感谢

**Comment by HomlesZhao** [comment]
@@你的依赖库给我一份行么？269258864@qq.com 谢谢了，我的注入后就闪退不知道为什么。。。@ githhhh
