### ISSUE TITLE
免越狱安装步骤，获取破壳微信

### ISSUE THREAD

**Issue by zhoupenghao** [buginux/WeChatRedEnvelop#127]
scp Clutch/clutch root@

**Comment by zhoupenghao** [comment]
生成出来的可执行文件就在 Clutch 目录下，将其拷贝到手机上：

1

	

scp Clutch/clutch root@<your.device.ip>:/usr/bin/   这步的时候

**Comment by buginux** [comment]
要用手机实际ip

**Comment by zhoupenghao** [comment]
是网络ip地址吗

**Comment by zhoupenghao** [comment]
scp Clutch/clutch root@192.168.1.118:/usr/bin/
ssh: connect to host 192.168.1.118 port 22: Connection refused
lost connection

**Comment by zhoupenghao** [comment]
我看了一下   ssh  sshd   都是正常的

**Comment by zhoupenghao** [comment]
bogon:.ssh zhoupenghao$ scp Clutch/clutch root@192.168.1.104:/usr/bin/
root@192.168.1.104's password: 
Permission denied, please try again.

**Comment by zhoupenghao** [comment]
2017-03-31 16:20:45.045 Clutch[630:4273] command: Prints installed applications
Installed apps:
1:   Flashlight • <com.7thg.flashlight>
iPhone:~ root#

**Comment by zhoupenghao** [comment]
安装的应用很多，这里  只出现了一个

**Comment by zhoupenghao** [comment]
能否直接把破壳的微信ipa包发一个，后面自己操作

**Comment by zhoupenghao** [comment]
是因为越狱手机是4s的关系吗

**Comment by zhoupenghao** [comment]
试了很多次，砸壳获取不到安装的多余应用，只有一个手电筒，是什么问题，4s   ，iOS 8.4

**Comment by buginux** [comment]
跟 4s 应该没有关系，砸壳的可以直接上 pp 助手下载就行了。

**Comment by zhoupenghao** [comment]
手机端的pp助手吗？    但是按照上面clutch拿到的   只有一个应用呢

**Comment by zhoupenghao** [comment]
otool -L WeChatRedEnvelop.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'WeChatRedEnvelop.dylib': No such file or directory.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed

**Comment by zhoupenghao** [comment]
$ optool install -c load -p "@executable_path/WeChatRedEnvelop.dylib" -t wechat/Payload/WeChat.app/WeChat
-bash: optool: command not found

**Comment by zhoupenghao** [comment]
到后面这步  optool  命令  找不到是什么原因呢

**Comment by zhoupenghao** [comment]
前面的步骤都成功了

**Comment by zhoupenghao** [comment]
存在optool可执行文件

**Comment by zhoupenghao** [comment]
安装完后，没有出现小助手，是哪里没成功吗？

**Comment by zhoupenghao** [comment]
使用的是pp助手直接下载的微信6.5.6  ipa包

**Comment by zhoupenghao** [comment]
是使用pp助手下载越狱应用中的微信

**Comment by zhoupenghao** [comment]
cp libsubstrate.dylib WeChatRedEnvelop.dylib wechat/Payload/WeChat.app
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory

**Comment by zhoupenghao** [comment]
install -c load -p "@executable_path/WeChatRedEnvelop.dylib" -t wechat/Payload/WeChat.app/WeChat
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...

**Comment by buginux** [comment]
你这些操作都是有问题的，你自己看下命令行相关的东西吧

**Comment by zhoupenghao** [comment]
这后面两个都有问题吗，直接复制的，其他步骤有问题吗

**Comment by zhoupenghao** [comment]
下载的ipa  对吗

**Comment by zhoupenghao** [comment]
好奇的点进来，这句回复没有什么帮助呀，抽个十几分钟来看，我也是太忙了老乡；

**Comment by buginux** [comment]
不是只有你忙啊老乡，ipa 可以下个 6.5.5 的试试。你这两个命令明显都是有问题的，这个问题你自己去解决啊

**Comment by zhoupenghao** [comment]
直接用mac上的PP助手下载越狱版本的微信  ipa  包可以的么

**Comment by zhoupenghao** [comment]
OK了，我之前试了另一种，发现旧版本的微信    不容易被检测，新版本的很容易
