### ISSUE TITLE
试验成功，没有证书怎么办

### ISSUE THREAD

**Issue by AemonChan** [buginux/WeChatRedEnvelop#129]
最新的微信6.5.7版，没有错误编译成功打包完成，没有证书没法测试最终的结果，有没有有证书的兄弟想试试的，我发ipa给你们。

**Comment by buginux** [comment]
可以使用个人证书打包

**Comment by AemonChan** [comment]
啥证书木有，我用Impactor_0.9.41，进行安装出现错误 ipa.cpp:438 cannot find .app/info.plist

**Comment by buginux** [comment]
开发者证书啊，每个人都有，怎么会没有

**Comment by zhoupenghao** [comment]
用自己的证书就行了
