### ISSUE TITLE
make编译过不去

### ISSUE THREAD

**Issue by maladoufupi** [buginux/WeChatRedEnvelop#131]
下载2.0的包  make之后提示No rule to make target `/tweak.mk'.  Stop  编译不过去

**Comment by Gensun** [comment]
localhost:test Genie$ git clone https://github.com/buginux/WeChatRedEnvelop.git
Cloning into 'WeChatRedEnvelop'...
remote: Counting objects: 410, done.
remote: Total 410 (delta 0), reused 0 (delta 0), pack-reused 410
Receiving objects: 100% (410/410), 702.23 KiB | 285.00 KiB/s, done.
Resolving deltas: 100% (228/228), done.
localhost:test Genie$ cd WeChatRedEnvelop/
localhost:WeChatRedEnvelop Genie$ make
Making all for tweak WeChatRedEnvelop...
 Compiling src/WBBaseViewController.m...
src/WBBaseViewController.m:11:9: fatal error: 'objc/objc-runtime.h' file not
      found
#import <objc/objc-runtime.h>
        ^
1 error generated.
make[2]: *** [obj/src/WBBaseViewController.m.777671c5.o] Error 1
make[1]: *** [internal-library-all_] Error 2
make: *** [WeChatRedEnvelop.all.tweak.variables] Error 2
我遇到这个问题，不知怎么解决

**Comment by buginux** [comment]
环境没配置好
