### ISSUE TITLE
提示会永久封号

### ISSUE THREAD

**Issue by zhoupenghao** [buginux/WeChatRedEnvelop#132]
有一个安装后，登了一个小号，然后好几天没去看，打开会被退出，说使用非官方客户端，再使用永久封号

他这个我都没使用了，怎么还检测到了

**Comment by zhoupenghao** [comment]
自己打包好后，登陆的小号，很久没去打开那个微信了，但是那个号在自己打包的客户端还是被检测到了

**Comment by zhoupenghao** [comment]
老乡来分析一下

**Comment by sukeay** [comment]
ASIdentifierManager 
advertisingIdentifier
ManualAuthAesReqData 
 @property(retain, nonatomic) NSString *bundleId; // @dynamic bundleId;
 @property(retain, nonatomic) NSString *clientSeqId; // @dynamic clientSeqId;
 @property(retain, nonatomic) NSString *deviceName; // @dynamic deviceName;
JailBreakHelper
- (bool)HasInstallJailbreakPluginInvalidIAPPurchase;
- (bool)HasInstallJailbreakPlugin:(id)arg1;
- (bool)IsJailBreak;
NSBundle
@property (readonly, copy) NSString *bundleIdentifier;

**Comment by xly1208** [comment]
@sukeay 这是微信检测盗版的位置？都修改哪几个值才能不被检测到呢？

**Comment by sukeay** [comment]
我改了这些不提示使用机器人了 但是提示使用非官方客户端 唉

**Comment by zhoupenghao** [comment]
对，就是非官方客户端

**Comment by FantasticSkyBaby** [comment]
@sukeay demo吗

**Comment by buginux** [comment]
一直用的越狱机，非越狱没有去跟进，不知道最近有更新检测机制吗

**Comment by FantasticSkyBaby** [comment]
@buginux 最近红包那块也加了检测 用一般抢红包的代码会被封

**Comment by buginux** [comment]
那我最近看下。。
