### ISSUE TITLE
可以单独弄个消息防撤回吗？

### ISSUE THREAD

**Issue by qin2** [buginux/WeChatRedEnvelop#134]
没有任何设置，直接 dylib，plist 两个东西就能有效的那种。

**Comment by buginux** [comment]
代码不是都有吗，你可以自己抽出来做一个单独的

**Comment by qin4** [comment]
就是不会所以。。。想求大神您亲自弄个。。。(*^__^*)

**Comment by buginux** [comment]
这个其实很简单，代码里面写得很清楚了，如果有兴趣的话可以自己研究下
