### ISSUE TITLE
红包插件可否增加几个功能？

### ISSUE THREAD

**Issue by woyiye** [buginux/WeChatRedEnvelop#135]
比如设置延时并可设置随机延时时长，再比如抢包声音提示（原版抢包声音即可），谢谢！

**Comment by buginux** [comment]
本来就有延时啊，随机延时原来有做过，后来删除了。原版抢包有什么声音，我怎么从来没有听过。

**Comment by chernglin** [comment]
@buginux , 能不能侦测最大的包，再来抢？

**Comment by buginux** [comment]
@zeroiszero 不能
