### ISSUE TITLE
抢自己在群里发的红包会在私聊里提示

### ISSUE THREAD

**Issue by ta01st** [buginux/WeChatRedEnvelop#14]
自己在群里发一个红包，会自动抢自己的红包，但是抢到红包的提示却在私聊里，不用插件手工抢是不会的

**Comment by buginux** [comment]
自己抢自己这个是故意写的，只要发在群聊里的红包都会抢，提示在私聊这个问题之前应该已经解决了才对

**Comment by liuyuning** [comment]
修改m_nsFromUsr为m_nsToUsr就在群里提示了。如下
[params safeSetObject:wrap.m_nsFromUsr forKey:@"sessionUserName"];	 ->
[params safeSetObject:wrap.m_nsToUsr forKey:@"sessionUserName"];
