### ISSUE TITLE
make package install 错误怎么解决啊？

### ISSUE THREAD

**Issue by qin4** [buginux/WeChatRedEnvelop#140]
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
==> Error: You do not have an SDK in /Library/Developer/CommandLineTools/Platforms/iPhoneOS.platform/Developer/SDKs or /opt/theos/sdks.
make: *** [before-all] Error 1

**Comment by buginux** [comment]
这是 sdk 没有定位到，使用 `xcode-select --print-path` 确认下下 Xcode 安装有没有问题

**Comment by qin4** [comment]
安装了但显示这个xcode-select: error: unable to get active developer directory, use `xcode-select --switch` to set one (or see `man xcode-select`)

**Comment by qin4** [comment]
在设置里面选了8.0然后显示/Users/PC/Desktop/Xcode.app/Contents/Developer

**Comment by qin4** [comment]
> Making all for tweak WEChatRedEnvelop…
==> Compiling src/WBBaseViewController.m (armv7)…
==> Compiling src/WBMultiSelectGroupsViewController.m (armv7)…
==> Compiling src/WBReceiveRedEnvelopOperation.m (armv7)…
src/WBReceiveRedEnvelopOperation.m:20:31: error: unknown type name 'WEChatRedEnvelopParam'; did you mean 'WeChatRedEnvelopParam'?
@property (strong, nonatomic) WEChatRedEnvelopParam *redEnvelopParam;
                              ^~~~~~~~~~~~~~~~~~~~~
                              WeChatRedEnvelopParam
src/WEChatRedEnvelopParam.h:11:12: note: 'WeChatRedEnvelopParam' declared here
@interface WeChatRedEnvelopParam : NSObject
           ^
src/WBReceiveRedEnvelopOperation.m:30:42: error: expected a type
- (instancetype)initWithRedEnvelopParam:(WEChatRedEnvelopParam *)param delay:(unsigned int)delaySeconds {
                                         ^
2 errors generated.
make[3]: *** [/Users/PC/Desktop/WXRedEnvelop/.theos/obj/debug/armv7/src/WBReceiveRedEnvelopOperation.m.52df58ab.o] Error 1
make[2]: *** [/Users/PC/Desktop/WXRedEnvelop/.theos/obj/debug/armv7/WEChatRedEnvelop.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [WEChatRedEnvelop.all.tweak.variables] Error 2

现在显示这个！！！！

**Comment by qin4** [comment]
成功了没问题了自己解决了！

**Comment by qin4** [comment]
微信最新版有bug消息撤回不到两分钟显示已经超过两分钟
