### ISSUE TITLE
iOS 10.3.2 微信 6.5.8.32 免越狱签名安装打开闪退！

### ISSUE THREAD

**Issue by qin2** [buginux/WeChatRedEnvelop#147]
在已越狱的手机提取：scp root@172.168.1.25:/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate ~/Desktop
重命名 libsubstrate.dylib

将 /usr/lib/libsubstrate.dylib 修改成 /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate

install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @loader_path/libsubstrate.dylib WeChatRedEnvelop.dylib

===============================================

PCdeMac:Desktop PC$ otool -L libsubstrate.dylib
libsubstrate.dylib (architecture armv6):
/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 7.0.0)
/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 100.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1198.0.0)
libsubstrate.dylib (architecture armv7):
/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 7.0.0)
/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 100.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1198.0.0)
libsubstrate.dylib (architecture arm64):
/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 100.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1198.0.0)

===============================================

PCdeMac:Desktop PC$ otool -L WeChatRedEnvelop.dylib
WeChatRedEnvelop.dylib (architecture armv7):
/Library/MobileSubstrate/DynamicLibraries/WeChatRedEnvelop.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.13.0)
/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1348.22.0)
/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.6.21)
@loader_path/libsubstrate.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
WeChatRedEnvelop.dylib (architecture arm64):
/Library/MobileSubstrate/DynamicLibraries/WeChatRedEnvelop.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.13.0)
/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1348.22.0)
/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.6.21)
@loader_path/libsubstrate.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)

===============================================

PCdeMac:Desktop PC$ /Users/PC/Desktop/WECHAT/optool install -c load -p "@executable_path/WeChatRedEnvelop.dylib" -t wechat/Payload/WeChat.app/WeChat
Found FAT Header
Found thin header...
Found thin header...
Inserting a LC_LOAD_DYLIB command for architecture: arm
Successfully inserted a LC_LOAD_DYLIB command for arm
Inserting a LC_LOAD_DYLIB command for architecture: arm64
Successfully inserted a LC_LOAD_DYLIB command for arm64
Writing executable to wechat/Payload/WeChat.app/WeChat...

**Comment by buginux** [comment]
改名的步骤错了，没有成功。

**Comment by qin2** [comment]
那么怎么改才对呢？

**Comment by qin2** [comment]
我参考这里的也不行：http://www.cnblogs.com/yate1996/p/6376008.html

**Comment by buginux** [comment]
我的那篇看过了吗

**Comment by qin2** [comment]
看过也差不多但还是闪退！求告知解决方法！

**Comment by buginux** [comment]
参考下这个 issue：https://github.com/buginux/WeChatRedEnvelop/issues/35，解决办法就是这样的，我没办法帮你操作，你还是得自己来。

**Comment by qin2** [comment]
不就是这个了命令了？install_name_tool -change /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate @loader_path/libsubstrate.dylib WeChatRedEnvelop.dylib

**Comment by w1nds** [comment]
没发现楼主的改名步骤有错呀，，我也遇到了同样的问题
