### ISSUE TITLE
请问下官网下的IDA运行出错

### ISSUE THREAD

**Issue by liuzhiyi1992** [buginux/WeChatRedEnvelop#15]
IDA 6.9 ，请问下朋友有碰到这个问题吗

![2016-05-11 4 13 05](https://cloud.githubusercontent.com/assets/13046550/15181962/a9e52670-17bc-11e6-9a59-4ad29f67b751.png)

**Comment by buginux** [comment]
不好意思，我用的是 hopper，没有碰到过这个问题

**Comment by liuzhiyi1992** [comment]
感谢
