### ISSUE TITLE
自动抢红包(OpenRedEnvelopesRequest)无法触发了

### ISSUE THREAD

**Issue by huakucha** [buginux/WeChatRedEnvelop#152]
WCRedEnvelopesLogicMgr *logicMgr = [[objc_getClass("MMServiceCenter") defaultCenter] getService:[objc_getClass("WCRedEnvelopesLogicMgr") class]];
                [logicMgr OpenRedEnvelopesRequest:params];

自动抢红包(OpenRedEnvelopesRequest)无法触发了

**Comment by buginux** [comment]
什么叫无法触发了？
