### ISSUE TITLE
现在这个版本的$ git clone https://github.com/buginux/WeChatRedEnvelop.git $ cd WeChatRedEnvelop $ make    出现这个

### ISSUE THREAD

**Issue by zhoupenghao** [buginux/WeChatRedEnvelop#156]
make
Makefile:6: /makefiles/common.mk: No such file or directory
Makefile:14: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.

这个是什么原因

**Comment by zhoupenghao** [comment]
缺少那2个文件吗，clone 下来是没有的

**Comment by dwj1210** [comment]
我也是这个问题。。求解谢谢。

**Comment by zhoupenghao** [comment]
老乡消失了，等他传吧

**Comment by buginux** [comment]
是 THEOS 的路径没配置

```
export THEOS=/opt/local/theos
```

**Comment by zhoupenghao** [comment]
tweak.mk提示这个文件不存在，common.mk这个也不存在

**Comment by zhoupenghao** [comment]
老乡你先试试用git上这个包，然后按照文档上执行，就会出现这个了

**Comment by zhoupenghao** [comment]
目前的所有免越狱的这个版本的人执行这个都会报这个错误，不是我一个人

**Comment by buginux** [comment]
上面已经回答了呀，是 THEOS 路径没配置好，在命令行执行下：

```
export THEOS=/opt/theos
```

**Comment by zhoupenghao** [comment]
export THEOS=/opt/theos   执行后   再make   还是提示文件不存在，路径还是不对

**Comment by zhoupenghao** [comment]
$ make
Makefile:6: /opt/local/theos/makefiles/common.mk: No such file or directory
Makefile:14: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.

**Comment by zhoupenghao** [comment]
打包完闪退呢

**Comment by buginux** [comment]
到哪一步闪退的？

**Comment by zhoupenghao** [comment]
安装完成后启动闪退

**Comment by zhoupenghao** [comment]
最新版的ipa

**Comment by buginux** [comment]
那可能是注入过程有问题，再确认下流程

**Comment by zhoupenghao** [comment]
奇怪了，还是会闪退，是非越狱版的，企业签，export THEOS=/opt/theos完，make完后步骤注入，也没报什么异常呢

**Comment by buginux** [comment]
这种情况，一般就是动态库没有加载到，所以才会崩的
