### ISSUE TITLE
博客文章 免越狱版 iOS 抢红包插件 执行下面的命令不好使

### ISSUE THREAD

**Issue by BeingX** [buginux/WeChatRedEnvelop#157]
![snip20170908_10](https://user-images.githubusercontent.com/16149297/30205188-b532a60c-94ba-11e7-9219-43ca9efa292b.png)

**Comment by zhoupenghao** [comment]
应该是缺少文件了

**Comment by BeingX** [comment]
是我电脑缺少吗

**Comment by zhoupenghao** [comment]
应该是博主没传

**Comment by buginux** [comment]
有啥问题

**Comment by BeingX** [comment]
问题已经提出了啊  第一条

**Comment by buginux** [comment]
。。你出了啥问题你要告诉我，你截张我文章的图，我怎么知道你出了啥问题？

**Comment by zhoupenghao** [comment]
执行make  提示缺少文件

**Comment by buginux** [comment]
#156 参考这个就可以了
