### ISSUE TITLE
 大神,可以 release 出 ipa 包吗?不需要签名

### ISSUE THREAD

**Issue by chenfengfeng** [buginux/WeChatRedEnvelop#160]
很多出错都是在加载动态库的时候出错,如果可以出个加载好的 ipa 包是最好的,我们自己去重签名就方便多了

**Comment by buginux** [comment]
微信经常更新，之前做过 ipa，很快就太旧了。我也没办法每次都去做个 ipa，太麻烦了~

**Comment by chenfengfeng** [comment]
好吧感谢回复
对了,在未越狱的教程里面,希望可以把其他需要安装的和准备的东西都说下,新人看了会觉得漏很多东西😁
