### ISSUE TITLE
咨询一个问题

### ISSUE THREAD

**Issue by zhoupenghao** [buginux/WeChatRedEnvelop#164]
老乡咨询一个问题，我要用Linux来进行ipa的注入重签，应该怎么做

**Comment by zhoupenghao** [comment]
非越狱的，企业签

**Comment by buginux** [comment]
Linux 的工具链不行吧

**Comment by zhoupenghao** [comment]
我也在找方案，目前只解决了linux重签，注入还没头绪，老乡你不是天天在弄吗，有没有什么方案

**Comment by zhoupenghao** [comment]
老乡帮我找个资源，iOS 11的

**Comment by buginux** [comment]
什么资料

**Comment by zhoupenghao** [comment]
iOS  11 获取应用的安装进度，如果获取不到获取安装的起点，我用itms-services:协议安装ipa，会弹出是否安装的提示，也就是无法获取到起点，安装进度iOS 11以下可以用私有api获取到，但iOS 11的上面模拟器可以获取，真机没有获取到，缺少似乎权限

**Comment by zhoupenghao** [comment]
老乡我发现PP助手有更新了，这块好像实现了，你知道这块的资料吗，旧的方法直接使用是不能用的

**Comment by zhoupenghao** [comment]
老乡咨询一个问题，您有做过越狱刷榜相关的功能吗
