### ISSUE TITLE
make package error

### ISSUE THREAD

**Issue by youxigit** [buginux/WeChatRedEnvelop#17]
==> Error: /Applications/Xcode.app/Contents/Developer/usr/bin/make package requires dpkg-deb.
make: **\* [internal-package-check] Error 1

**Comment by buginux** [comment]
看错误信息你好像没有配置 dpkg-deb 啊

**Comment by niehaili** [comment]
弱弱的问一下  需要怎么配置呢？http://bbs.feng.com/read-htm-tid-9669234.html 介个？？

**Comment by buginux** [comment]
http://www.swiftyper.com/2016/01/25/ios-tweak-install-guide/ 看下我这篇博客
