### ISSUE TITLE
2017-12-14 12:11:12.211563+0800 WeChat[5389:1292964]  NanoCrashGuardInitialize (lldb) 

### ISSUE THREAD

**Issue by zhoupenghao** [buginux/WeChatRedEnvelop#170]
2017-12-14 12:11:12.211563+0800 WeChat[5389:1292964] 
NanoCrashGuardInitialize
(lldb) 
这个启动的时候挂了，什么原因

**Comment by zhoupenghao** [comment]
2017-01-03 12:26:29.931101 WeChat[2249:425996] [DYMTLInitPlatform] platform initialization successful
2017-01-03 12:26:30.136132 WeChat[2249:425858] [AntiAntiDebug Init]
2017-01-03 12:26:30.212073 WeChat[2249:425858] Method Trace is disable
2017-01-03 12:26:30.221093 WeChat[2249:425858] 
NanoCrashGuardInitialize

**Comment by zhoupenghao** [comment]
2017-01-03 12:40:09.250198 WeChat[2271:428904] 
NanoCrashGuardInitialize
2017-01-03 12:40:28.836954 WeChat[2271:428904] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x18ee0d1b8 0x18d84455c 0x18eceb870 0x18ecf75fc 0x105f622f0 0x194d346a4 0x194f44a98 0x194f4a808 0x194f5f104 0x194f477ec 0x1909e392c 0x1909e3798 0x1909e3b40 0x18edbab5c 0x18edba4a4 0x18edb80a4 0x18ece62b8 0x194d2d7b0 0x194d28534 0x1001bb840 0x18dcc95b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by zhoupenghao** [comment]
看来有空内容

**Comment by zhoupenghao** [comment]
看来有空内容，nsinvalidargumentexception  这个是请求权限吗，注入以后的包怎么会出现这个问题呢

**Comment by zhoupenghao** [comment]
看来有空内容，是注入有问题吗

**Comment by zhoupenghao** [comment]
libc++abi.dylib`__cxa_throw:
->  0x18d832efc <+0>:   stp    x22, x21, [sp, #-0x30]!
    0x18d832f00 <+4>:   stp    x20, x19, [sp, #0x10]
    0x18d832f04 <+8>:   stp    x29, x30, [sp, #0x20]
    0x18d832f08 <+12>:  add    x29, sp, #0x20            ; =0x20 
    0x18d832f0c <+16>:  mov    x19, x2
    0x18d832f10 <+20>:  mov    x20, x1
    0x18d832f14 <+24>:  mov    x21, x0
    0x18d832f18 <+28>:  bl     0x18d832b18               ; __cxa_get_globals
    0x18d832f1c <+32>:  mov    x22, x0

**Comment by zhoupenghao** [comment]
定位在didFinishLaunchingWithOptions   CContactMgr *contactMgr = [[%c(MMServiceCenter) defaultCenter] getService:%c(CContactMgr)]   返回是空的，之后的内容也都是空的

**Comment by zhoupenghao** [comment]
微信版本6.6.0

**Comment by zhoupenghao** [comment]
把didFinishLaunchingWithOptions  代码去掉，再重新跑一下，没有挂掉了，账号信息输入登录的时候  显示网络出错，轻触屏幕重新加载：-1202

登不进去呢，老乡人呢

**Comment by buginux** [comment]
唔，那个是获取联系人信息的，有可能是取到空信息了

**Comment by zhoupenghao** [comment]
应该怎么处理呢

**Comment by zhoupenghao** [comment]
弄好了，老乡转账回调成功失败，你有办法监听到吗

**Comment by buginux** [comment]
你想做什么

2018-01-04 15:57 GMT+08:00 zhoupenghao <notifications@github.com>:

**Comment by zhoupenghao** [comment]
研究一下，好像有很多种支付类型，指导一下，这块

**Comment by buginux** [comment]
老铁你做灰产的吧，各种研究啊

**Comment by zhoupenghao** [comment]
0.0学习啊，灰产之前那个他们说要做刷榜，有现成的让我改，还问你了来着，不过我推掉了

**Comment by zhoupenghao** [comment]
指导一下回调在哪里能监听到

**Comment by zhoupenghao** [comment]
@buginux

**Comment by buginux** [comment]
这个我也得去看啊，你自己去找下不是比在这问更快吗。我没去看也是不知道的。
