### ISSUE TITLE
检测非法

### ISSUE THREAD

**Issue by wikiInit** [buginux/WeChatRedEnvelop#180]
检测非法，老乡有什么好建议或者办法，或者降低概率

**Comment by zhoupenghao** [comment]
您现在使用的版本是哪个，会比较稳定吗

**Comment by uniqueque** [comment]
用小号 还是平时正常的号

**Comment by zzBelieve** [comment]
检测非法.. 在用就被封号了
<img width="433" alt="qq20180124-1 2x" src="https://user-images.githubusercontent.com/10309351/35316352-251bb842-010c-11e8-864a-f8630c94417e.png">

**Comment by zhoupenghao** [comment]
@buginux 老乡，这个有什么好的解决方案。

**Comment by zhoupenghao** [comment]
@uniqueque 都会啊，用了好多年的WX的号也会

**Comment by zhoupenghao** [comment]
你们用的是改bundleid的还是原签的

**Comment by buginux** [comment]
斗不过微信，年末了抓得严

**Comment by zhoupenghao** [comment]
@buginux 你这边也会吗
