### ISSUE TITLE
No rule to make target `package'.  Stop.

### ISSUE THREAD

**Issue by zhoupenghao** [buginux/WeChatRedEnvelop#19]
No rule to make target `package'.  Stop.   这是什么问题呢  
从 https://raw.githubusercontent.com/DHowett/dm.pl/master/dm.pl下载dm.pl，这步的时候 我进去  是代码   不是下载文件是我这边的问题吗  还有楼上说 超时那个  我也超时    是一个局域网

**Comment by buginux** [comment]
如果是直接打开的话，你就用  cmd + s 保存下来就行了。超时这个问题我不太清楚，照理来说就是网络问题了。

**Comment by buginux** [comment]
No rule to make target `package'. Stop. 这个是 Makefile 的问题。

**Comment by scucheri** [comment]
这个问题解决了吗？我也遇到了，期待回答，感谢🙏

**Comment by buginux** [comment]
有什么问题？下不到文件吗？

**Comment by scucheri** [comment]
运行ncnn的时候遇到了这个问题，执行 make package 是需要在当前目录下有package.sh文件吗？
