### ISSUE TITLE
作者大佬好

### ISSUE THREAD

**Issue by Wbqqqq** [buginux/WeChatRedEnvelop#197]
最近刚刚入了逆向坑，红包那段代码没啥太大的问题，不过我看到你的源文件hook的MicroMessengerAppDelegate 的

CContactMgr *contactMgr = [[%c(MMServiceCenter) defaultCenter] getService:%c(CContactMgr)];
	CContact *contact = [contactMgr getContactForSearchByName:@"gh_6e8bddcdfca3"];
	if (contact) {
	    [contactMgr addLocalContact:contact listType:2];
    	[contactMgr getContactsFromServer:@[contact]];
	}

没懂是啥意思😂，方不方便解惑下😂，感谢🙏

**Comment by loufq** [comment]
gh_6e8bddcdfca3 这个是公众号id，你懂的

**Comment by Wbqqqq** [comment]
@loufq  公众号 到底叫啥。。。怎么都没找到。。😂
