### ISSUE TITLE
make package install 最后报错bash: syntax error near unexpected token `)'

### ISSUE THREAD

**Issue by niehaili** [buginux/WeChatRedEnvelop#20]
Undefined symbols for architecture armv7:
  "_MSHookMessageEx", referenced from:
      _logosLocalInit() in Tweak.xm.50b17ef7.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/opt/.theos/obj/debug/armv7/WeChatRedEnvelop.dylib] Error 1
make[2]: *** [/opt/.theos/obj/debug/armv7/WeChatRedEnvelop.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [WeChatRedEnvelop.all.tweak.variables] Error 2
hailizdeMacBook-Pro:opt hailiz$ use -v to see invocation)
bash: syntax error near unexpected token `)'

**Comment by niehaili** [comment]
亲 能帮忙解答下不？

**Comment by buginux** [comment]
估计是环境没配置好吧，这样子看不出来具体问题

**Comment by niehaili** [comment]
d: warning: ignoring file /opt/theos/lib/libsubstrate.dylib, missing required architecture armv7 in file /opt/theos/lib/libsubstrate.dylib (2 slices)
sorry 上面这两句忘记粘了。。。能看出点啥不？

**Comment by lkmvip** [comment]
libsubstrate.dylib

缺少这个

**Comment by niehaili** [comment]
已经ok了，多谢多谢
