### ISSUE TITLE
重签名成功，安装成功，但是打开crash，有日志

### ISSUE THREAD

**Issue by Bofearless** [buginux/WeChatRedEnvelop#203]
Date/Time:           2018-12-03 17:54:11.0735 +0800
Launch Time:         2018-12-03 17:54:10.6851 +0800
OS Version:          iPhone OS 12.0.1 (16A404)
Baseband Version:    10.10.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate | Referenced from: /var/containers/Bundle/Application/EA0B5334-08D8-4697-AD32-8125F23F7C9D/WeChat.app/WeChatRedEnvelop.dylib | Reason: image not found
Triggered by Thread:  0

**Comment by Bofearless** [comment]
貌似你这个库，在最新的微信ipa中无法动态加载？

**Comment by buginux** [comment]
你没有注入 CydiaSubstrate 这个库

**Comment by Bofearless** [comment]
> 你没有注入 CydiaSubstrate 这个库

@buginux 好的，我解决重新签名看下，谢谢啦

**Comment by Bofearless** [comment]
> 你没有注入 CydiaSubstrate 这个库

确实如此，非常感谢！
