### ISSUE TITLE
被检测到插件了

### ISSUE THREAD

**Issue by Zhulmin** [buginux/WeChatRedEnvelop#204]
安装的第一天  收到警告...

`Current WeChat account is
suspected of using an
unauthorized WeChat plug-in,
non-official app, or simulator.
UninstaIl the unauthorized
software or plug-in or download
WeChat from a legitimate source
and use it appropriately. If you
continue to unauthorized
software, your account may be
banned.`

微信可以检测   bundle id不一样  就不是官方应用吧?

**Comment by buginux** [comment]
老哥，微信现在抓得很严，建议用越狱机，不要用重签包，很容易被封。

**Comment by HermanForHeQian** [comment]
昨晚弄了一个，早上就提醒我再用就封号，有什么防封措施呢

**Comment by Zhulmin** [comment]
> 昨晚弄了一个，早上就提醒我再用就封号，有什么防封措施呢
@HermanForHeQian 只能越狱了

**Comment by Zhulmin** [comment]
> > 昨晚弄了一个，早上就提醒我再用就封号，有什么防封措施呢

@HermanForHeQian  只能越狱了    

非越狱机重签名, 会被检测出和官方app的签名不同.  
越狱机才能绕过签名
