### ISSUE TITLE
DYLD, Symbol not found: __dyld_get_all_image_infos 错误，这里有一个大坑。

### ISSUE THREAD

**Issue by Bofearless** [buginux/WeChatRedEnvelop#206]
Termination Description: DYLD, Symbol not found: __dyld_get_all_image_infos | Referenced from: /var/containers/Bundle/Application/8B89308F-EF52-43B8-B6BC-1AD949737E0D/WeChat.app/libsubstrate.dylib | Expected in: dyld shared cache | in /var/containers/Bundle/Application/8B89308F-EF52-43B8-B6BC-1AD949737E0D/WeChat.app/libsubstrate.dylib

以上是详细的crash日志，这个不是动态库注入的问题，是libsubstrate.dylib这个库本身的问题。
libsubstrate.dylib这个库在不同的版本上是不兼容得，即使已经越狱后拿到的。比如iOS9越狱里拿到的，在iOS11.x 以上系统无法使用，就会crash，报这个crash日志。
也就是说，目前注入不同的libsubstrate.dylib，不是所有iOS系统都可以正常打开使用，我目前的问题就是这个：亲测，动态库注入成功，iOS9.x-iOS10.x 系统安装、打开使用OK，iOS11 和 iOS12 以上就会出现上面的crash，目前未找到解决办法。

如果哪位有最新版的libsubstrate.dylib，可以分享下，要不然高版本的iOS系统的童鞋们（比如iOS12）就没法玩啦，哈哈😄。

**Comment by Chillbon** [comment]
看来ios12/13就玩不了了

**Comment by Bofearless** [comment]
closed

**Comment by Bofearless** [comment]
closed
