### ISSUE TITLE
只用了一次抢红包就被提示非客户端

### ISSUE THREAD

**Issue by hanjianfei** [buginux/WeChatRedEnvelop#207]
我用了扫码登录的功能，登陆第三方的应用，还是登陆微信pc端，不知道是不是这个检测出来的 还是 因为抢了一次红包检测出来的。

**Comment by Bofearless** [comment]
@hanjianfei 我也是，被检测出来了，请问大佬有解决方案吗？

**Comment by buginux** [comment]
建议使用越狱机，非越狱的容易被检测
