### ISSUE TITLE
新版微信

### ISSUE THREAD

**Issue by CoderHL** [buginux/WeChatRedEnvelop#208]
新版微信,不管是我自己通过tweak生成的插件,还是直接在Cydia下载的插件都找不到设置入口,对于博主的这个tweak源码是不是已经不适用最新微信了?

**Comment by zhangdongpo** [comment]
我的也找不到，以前直接在 Cydia 下载之后就可以看到入口么@CoderHL

**Comment by CoderHL** [comment]
这个插件之前没有用过@zhangdongpo

**Comment by DKJone** [comment]
7.0之后的微信列表添加cell逻辑改了，7.0之前可以用

**Comment by zhangdongpo** [comment]
作者赶紧更新一下啊，快过年了[捂脸]

**Comment by weivvip** [comment]
谁有抢红包，转发等功能齐全的源码出售啊？

**Comment by buginux** [comment]
新版微信的设置界面改名了，所以没办法进到设置界面，这个我最近处理下吧

**Comment by buginux** [comment]
源码已经更新，正在上传商店中...
