### ISSUE TITLE
有没有整成功的？ 我们建个群一起研究？

### ISSUE THREAD

**Issue by Gensiss** [buginux/WeChatRedEnvelop#211]
有没有整成功的？
我们建个群一起研究？
微信号Genesis-x
加我备注“红包插件”

**Comment by kxinds** [comment]
> @Gensiss wechat-6.7.4版本，我成功了😄
ipa分享下噻

**Comment by haheha** [comment]
> @Gensiss wechat-6.7.4版本，我成功了😄

老铁加个微信 请教一下

**Comment by Bofearless** [comment]
@Gensiss 你分享个二维码啊

**Comment by Gensiss** [comment]
> @Gensiss 你分享个二维码啊
没法分享群二维码啊
加我微信号
Genesis-x
拉你进群

**Comment by Gensiss** [comment]
@Bofearless 没法分享群二维码啊
加我微信号
Genesis-x
拉你进群

**Comment by haheha** [comment]
> @Gensiss 你分享个二维码啊
scp root@192.168.1.248:/usr/lib/libsubstrate.dylib ~/Desktop                    
ssh: connect to host 192.168.1.248 port 22: Connection refused

不想 越狱手机 卡在 这一步了，不知道咋搞了

**Comment by Gensiss** [comment]
![default](https://user-images.githubusercontent.com/16629478/52038617-c64b5700-256d-11e9-937e-adbfc4ecf068.png)

**Comment by buginux** [comment]
7.0 版本已经更新，大家可以试一下。

**Comment by x1917166** [comment]
二维码失效了

**Comment by x1917166** [comment]
@Gensiss二维码失效了
