### ISSUE TITLE
支持微信7.0

### ISSUE THREAD

**Issue by zjjno** [buginux/WeChatRedEnvelop#212]
https://github.com/zjjno/WeChatRedEnvelop
fork更新支持了微信7.0 等buginux更新我就删除fork

**Comment by wooter-s** [comment]
@zjjno 能说下使用流程吗，尝试使用fork分支构建的动态库设置里没有效果

**Comment by zhihaozhang** [comment]
cydia里能否更新一下？

**Comment by cjqzdm** [comment]
@zjjno 能说下使用流程吗

**Comment by dakezuo** [comment]
@zjjno 我导入到微信里了，也有微信小助手，开关也是开启的，但好像并没有能够自动抢红包

**Comment by zjjno** [comment]
> @zjjno 我导入到微信里了，也有微信小助手，开关也是开启的，但好像并没有能够自动抢红包

只抢群红包 私聊红包不抢的

**Comment by weivvip** [comment]
谁有抢红包，转发等功能齐全的源码出售啊？

**Comment by dakezuo** [comment]
@zjjno 了解，我测试下

**Comment by xxNB** [comment]
@zjjno 如何安装，非越狱可以吗

**Comment by buginux** [comment]
等我更新下再上传到 cydia

**Comment by python10086** [comment]
有上传到cydia吗，求cydia下载

**Comment by buginux** [comment]
源码已经更新，商店正在上传中...
