### ISSUE TITLE
新建了一个项目，使用了大佬项目里抢红包的逻辑

### ISSUE THREAD

**Issue by DKJone** [buginux/WeChatRedEnvelop#213]
如果允许我将把所有代码公开，不行的话会删除相关代码[项目地址](https://github.com/DKWechatHelper/DKWechatHelper)
![img_0223](https://user-images.githubusercontent.com/15855089/51583739-daa7a800-1f0c-11e9-983d-e61f425fbae3.jpg)

**Comment by DKJone** [comment]
源码里有一部分的防封号的逻辑在dkhelperDylib.m里，另外你下载全部源码后用XCode安装的bundleID就是“com.tencent.xin”。这些都是防止封号的，但是不是绝对的安全，还是可以被微信检测出来的。

**Comment by buginux** [comment]
没事，本来就是开源的
