### ISSUE TITLE
红包参数问题

### ISSUE THREAD

**Issue by xieHugo** [buginux/WeChatRedEnvelop#22]
params[@"msgType"] = nativeUrlDict[@"msgtype"] ?: @"1";
                params[@"sendId"] = nativeUrlDict[@"sendid"] ?: @"";
                params[@"channelId"] = nativeUrlDict[@"channelid"] ?: @"1";
                params[@"nickName"] = [selfContact getContactDisplayName] ?: @"小锅";
                params[@"headImg"] = [selfContact m_nsHeadImgUrl] ?: @"";
                params[@"nativeUrl"] = [[wrap m_oWCPayInfoItem] m_c2cNativeUrl] ?: @"";
                params[@"sessionUserName"] = wrap.m_nsFromUsr ?: @"";
这些参数怎么知道的？有没有自动抢的金额的这个参数？

**Comment by nicolastinkl** [comment]
#import "WXPBGeneratedMessage.h"

@class BaseResponse, NSString, SKBuiltinBuffer_t;

@interface HongBaoRes : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* errorMsg;
@property(assign, nonatomic) int errorType;
@property(assign, nonatomic) int cgiCmdid;
@property(retain, nonatomic) NSString* platMsg;
@property(assign, nonatomic) int platRet;
@property(retain, nonatomic) SKBuiltinBuffer_t* retText;
@property(retain, nonatomic) BaseResponse* baseResponse;
+(void)initialize;
@end


所有返回的参数都在HongbaoRes.m里

**Comment by xieHugo** [comment]
恩，但是发送打开红包请求的时候，红包金额的参数不起作用，请问你是哪个有效参数吗？

**Comment by buginux** [comment]
我是使用 lldb 动态调试拿到参数的

**Comment by xieHugo** [comment]
对，打印HongBaoRes的retText里能看到参数，但是就是没有可以自己设置抢的红包金额，不知道能不能实现，听说这个计算是服务端算的

**Comment by buginux** [comment]
红包金额肯定是不能设置的，这种东西不可能在客户端设置的，不用考虑了。

**Comment by xieHugo** [comment]
但是市面上那么多的抢红包器，听说能实现这个功能，没搞懂怎么实现
