### ISSUE TITLE
好像被检测出来了

### ISSUE THREAD

**Issue by leibaozai** [buginux/WeChatRedEnvelop#221]
你的微信版本过低，请升级至最新版本微信后再登录微信。在登录的时候弹框，是在微信7.0版本上

**Comment by leibaozai** [comment]
在pp助手重新下载微信7.0.4版本，重新试了一次，又可以了。感谢

**Comment by wenbobao** [comment]
你好，能分享个7.0.4的ipa吗，pp助手现在是708的
