### ISSUE TITLE
老版本微信闪退

### ISSUE THREAD

**Issue by zlhdd108** [buginux/WeChatRedEnvelop#223]
目前还是用的老版本的微信,6.7.4；
iOS版本是8.1.1
已完美越狱，但是使用最新的版本会出现闪退现象，上一个版本没有问题，今天点到cydia的时候不小心点到更新所有了，结果就升级到新版本，出现了闪退的现象，不知道能否回退版本？

**Comment by zlhdd108** [comment]
找到方法了，http://tweakupdates.com/pkg/com.swiftyper.wechatredenvelop下载老版本的deb，用iFunBox放到Cydia重新安装即可

**Comment by buginux** [comment]
更新版本之后没有做旧版兼容，感谢提供解决办法。
