### ISSUE TITLE
最后一步报错

### ISSUE THREAD

**Issue by DexSinis** [buginux/WeChatRedEnvelop#23]
In file included from <built-in>:349:
In file included from <command line>:5:
/Users/a000/Downloads/WeChatRedEnvelop-master-2/theos/Prefix.pch:6:10: fatal error:
      '_Prefix/NullabilityCompat.h' file not found
        #import <_Prefix/NullabilityCompat.h>
                ^
1 error generated.
make[3]: *** [/Users/a000/Downloads/WeChatRedEnvelop-master-2/.theos/obj/debug/armv7/Tweak.xm.61df67f4.o] Error 1
make[2]: *** [/Users/a000/Downloads/WeChatRedEnvelop-master-2/.theos/obj/debug/armv7/WeChatRedEnvelop.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [WeChatRedEnvelop.all.tweak.variables] Error 2

**Comment by DexSinis** [comment]
版本号是6.3.22

**Comment by buginux** [comment]
在 make 之前先执行命令：
```
export THEOS=/opt/theos
```

**Comment by DexSinis** [comment]
执行了 依然存在这个问题
export JAVA_HOME="$JAVA_7_HOME"
export M2="/Users/a000/工作/BigSmall/ide/apache-maven/bin"
export PATH="$JAVA_HOME/bin:$PATH:$M2"
export PATH="/opt/subversion/bin:$PATH"
export GRADE_HOME="/Users/a000/工作/BigSmall/ide/gradle-2.6"
export "PATH=/opt/local/bin:/opt/local/sbin:$PATH:$GRADE_HOME/bin"
export THEOS="/opt/theos"

**Comment by DexSinis** [comment]
重新安装就好 执行原来的
export THEOS=/opt/theos
# 如果之前已经安装过 theos，请先删除，然后下载最新版
rm -rf $THEOS
sudo git clone --recursive https://github.com/theos/theos.git $THEOS
