### ISSUE TITLE
插件装上了，但是不起作用

### ISSUE THREAD

**Issue by DexSinis** [buginux/WeChatRedEnvelop#24]
这个需要一直打开微信么 版本号6.3.22

**Comment by buginux** [comment]
是的，没有对后台进行处理，进入后台后会被系统关掉，所以只能一直在前台运行。

**Comment by DexSinis** [comment]
估计这个不好解决，能不能模拟播放一首无声音乐占用后台

**Comment by buginux** [comment]
如果需要后台处理，可以到 Cydia 下载 watchdog，这个插件可以允许将应用程序放到后台而不被系统终止。
