### ISSUE TITLE
你好,想基于这个原理定制一个插件

### ISSUE THREAD

**Issue by heycpp** [buginux/WeChatRedEnvelop#25]
这个抢红包插件的原理是监控消息,
我想基于这个原理定制一个批量处理邀请入群动作的插件,不知大大是否有时间研究?
批量处理微信好友邀请入群链接

就3个功能

1.后台自动接受入群
2.后台设置保存通讯录
3.后台设置消息免打扰的插件

狗神的思路:
http://bbs.iosre.com/t/h5/3328
相关的实现?
http://bbs.iosre.com/t/topic/3353

我的企鹅号是987123
加我详细聊,验证答案随便打.

**Comment by buginux** [comment]
这个狗神已经实现过了，具体的话，可以直接在论坛提问就行了~
