### ISSUE TITLE
教程是这个吗?

### ISSUE THREAD

**Issue by androidcn** [buginux/WeChatRedEnvelop#3]
http://joeyio.com/ios/2014/01/01/make-a-mobile-substrate-tweak-using-theos/

**Comment by buginux** [comment]
并不是哦，这篇不是我写的教程。
我的教程地址是：http://www.swiftyper.com/ios-tweak-install-guide

**Comment by androidcn** [comment]
@buginux 谢谢
另外如何卸载

**Comment by androidcn** [comment]
'''
make package install
Makefile:6: theos/makefiles/common.mk: No such file or directory
Makefile:12: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.
'''

**Comment by buginux** [comment]
1. 卸载的话可以直接在cydia里面找到你已经安装过的tweak，然后就可以进行卸载。
2. 我的教程里漏了一步，实在抱歉，我已经更新了，你可以再去看看，主要就是**安装Theos**这一步漏掉了。感谢指出。
