### ISSUE TITLE
请问您用过logify.pl么，有些问题想请教

### ISSUE THREAD

**Issue by FurionXin** [buginux/WeChatRedEnvelop#30]
我自己在练习编写Tweak的时候，用到了logify.pl用于方法的追踪，可是在编写makefile的时候，加上wxmsgcatch_CFLAGS = -fno-objc-arc这句，编译还是文件类型不符，看网上说要用mrc编译xm文件，请问您遇到过么，该怎么解决呢~~

**Comment by buginux** [comment]
http://bbs.iosre.com/t/app-ios/5985 这篇文章里面有讲到了 logify.pl 的使用，可以参考下
