### ISSUE TITLE
如果想暂时关闭功能，是不是只有先卸载，再重装？

### ISSUE THREAD

**Issue by STingLee666** [buginux/WeChatRedEnvelop#31]
RT，如果是的话，能加个开关吗？

**Comment by buginux** [comment]
是的，现在暂时没有添加关闭功能，如果要暂停使用，只能先卸载。

**Comment by STingLee666** [comment]
那么卸载之后，又得再执行上面的步骤才能装上去吗，第二次安装有没有简便一点的方法？

**Comment by buginux** [comment]
已经更新打开与关闭抢红包功能，重新安装后到“我的” -> “设置”里面就可以看到了。

**Comment by STingLee666** [comment]
简直优秀啊，逆向工程确实挺有意思的，有空也想研究下。
