### ISSUE TITLE
make之后出现以下错误

### ISSUE THREAD

**Issue by kakaluo** [buginux/WeChatRedEnvelop#32]
![image](https://cloud.githubusercontent.com/assets/7160316/21480172/7eba63ec-cb95-11e6-912f-53e87d6053d7.png)

**Comment by buginux** [comment]
是不是 Makefile 当中没有导入 UIKit 库。

**Comment by kakaluo** [comment]
UIKit导入了的，感觉是theos安装有问题，我换了个git就可以了，现在已经成功make出dylib，谢谢！
