### ISSUE TITLE
theos是替身文件，make报错

### ISSUE THREAD

**Issue by fidetro** [buginux/WeChatRedEnvelop#33]
Makefile:6: theos/makefiles/common.mk: No such file or directory
Makefile:12: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.

**Comment by buginux** [comment]
EXPORT THEOS=/opt/theos

**Comment by hongdong** [comment]
我也是这个报错、怎么办

**Comment by buginux** [comment]
在命令行中输入 `EXPORT THEOS=/opt/theos`

**Comment by NikoXu** [comment]
重装一下theos试试, 删除旧的
然后`git clone --recurse-submodules git@github.com:theos/theos.git`

**Comment by ifgyong** [comment]
我也是同样的错误啊！

**Comment by buginux** [comment]
@ifgyong 上面提的方法你试了吗。

**Comment by Cui-y** [comment]
配置环境变量还是报错

**Comment by Cui-y** [comment]
Makefile:6: /opt/theos/makefiles/common.mk: No such file or directory
Makefile:14: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.

执行export命令还是报上面的错误
