### ISSUE TITLE
最后一步错误

### ISSUE THREAD

**Issue by wskiwhexing** [buginux/WeChatRedEnvelop#35]
第一：make 出来的包没有看到libsubstrate.dylib 没有substrate 库

$ otool -L WeChatRedEnvelop.dylib
WeChatRedEnvelop.dylib (architecture armv7):
	/Library/MobileSubstrate/DynamicLibraries/WeChatRedEnvelop.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.13.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1348.22.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.6.21)
	/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
WeChatRedEnvelop.dylib (architecture arm64):
	/Library/MobileSubstrate/DynamicLibraries/WeChatRedEnvelop.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.13.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1348.22.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.6.21)
	/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)

**Comment by buginux** [comment]
1、在你那边的是 /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate 这个库，具体的可以参考 [http://bbs.iosre.com/t/ios/6119/26](http://bbs.iosre.com/t/ios/6119/26) 这个帖子，里面有一个跟你情况一样的，我给了解释。
2、 关于第二个应该是你 github 没有添加 ssh-key 的问题，可以参考下 [https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account) 这个链接。

**Comment by buginux** [comment]
对，这个库是只有越狱手机才有的那个 ip 就是指越狱手机的 ip

**Comment by wskiwhexing** [comment]
用网上下的别人的文件应该不可以么？我不想手机越狱呀。。。

**Comment by wskiwhexing** [comment]
还有哦  拷出来，改名成 libsubstrate.dylib，然后在 -change 后面把 /usr/lib/libsubstrate.dylib 改成你的 /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate。 
拷出到桌面了 
scp root@<your.device.ip>:/usr/lib/libsubstrate.dylib ~/Desktop
$ install_name_tool -change /usr/lib/libsubstrate.dylib @loader_path/libsubstrate.dylib WeChatRedEnvelop.dylib

为什么不是 install_name_tool -change ~/Desktop/libsubstrate.dylib @loader_path/libsubstrate.dylib WeChatRedEnvelop.dylib  而是 /usr/lib/libsubstrate.dylib 呢？ 还有 @loader_path 这个地址是不用修改的对吧，就是@loader_path就代表获取app 内的相对地址吧

**Comment by buginux** [comment]
照理来说，是可以拿别人的，但是我没试过，不敢保证。

@loader_path 不用改，照着写就行了。

**Comment by wskiwhexing** [comment]
我按照步骤全部弄好了，也可以弄出ipa  能正常安装，但是要闪退。纠结啦。。 手机不想越狱。。 我在网上下的libsubstrate.dylib 文件。。 不知道是不是这个文件的问题

**Comment by buginux** [comment]
这是我用的，你可以试试。

链接: https://pan.baidu.com/s/1qXBqHSo 密码: efvy

只能帮你到这了。

**Comment by wskiwhexing** [comment]
哈哈，那就再帮一下吧非常感谢，把你手机里的  /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate 这个库也拷出来给我一下。3q

**Comment by buginux** [comment]
刚刚发的就是这个库

**Comment by wskiwhexing** [comment]
已经解决问题，非常感谢。

**Comment by buginux** [comment]
👍

**Comment by renzifeng** [comment]
我遇到这问题了，使用提供的ibsubstrate.dylib还是闪退

**Comment by devwcq** [comment]
@buginux 我也是用你提供的libsubstrate.dylib,注入以后也是老是闪退。。。

**Comment by devwcq** [comment]
@wskiwhexing 你怎么解决的？

**Comment by renzifeng** [comment]
@devwcq 你没注入成功吧

**Comment by devwcq** [comment]
@renzifeng 注入以后 出现下面这些 提示 ，这应该算注册成功了吧。
Found FAT Header
Found thin header...
Found thin header...
Inserting a LC_LOAD_DYLIB command for architecture: arm
Successfully inserted a LC_LOAD_DYLIB command for arm
Inserting a LC_LOAD_DYLIB command for architecture: x86_64
Successfully inserted a LC_LOAD_DYLIB command for x86_64
Writing executable to wechat/Payload/WeChat.app/WeChat...

**Comment by buginux** [comment]
@devwcq 是的

**Comment by devwcq** [comment]
@buginux 那就尴尬了，我估计是微信最新包不行了。

**Comment by devwcq** [comment]
@buginux 为什么我会出现x86_64不出现arm64？😂

**Comment by buginux** [comment]
@devwcq 不是很清楚，你是使用 PP 助手的吗？你自己手动砸一个试试呢。

**Comment by devwcq** [comment]
@buginux 嗯，我是在pp助手越狱市场下载获取的微信ipa包，好吧，我用越狱机手动砸包试试，tks。

**Comment by fujinlin** [comment]
Found FAT Header
Found thin header...
Found thin header...
Inserting a LC_LOAD_DYLIB command for architecture: arm
Successfully inserted a LC_LOAD_DYLIB command for arm
Inserting a LC_LOAD_DYLIB command for architecture: arm64
Successfully inserted a LC_LOAD_DYLIB command for arm64
Writing executable to Payload/WeChat.app/WeChat...

为什么我这安装也是闪退呀？ /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate  我的也是这个，谁有这个包提供下，非常感谢

**Comment by jacinzhang** [comment]
@buginux  我的注入后提示这个
```shell
WeChat.app/WeChat
Found thin header...
Inserting a LC_LOAD_DYLIB command for architecture: arm64
Successfully inserted a LC_LOAD_DYLIB command for arm64
Writing executable to wechat/Payload/WeChat.app/WeChat...
```

跟你们的不太一样啊，这是成功还是失败的？

**Comment by gank0326** [comment]
@wskiwhexing  我也遇到了同样的问题，你最后怎么解决的！下载了别人的libsubstrate.dylib  
下一步该怎么做？

**Comment by dakezuo** [comment]
可以在github提供下/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate这个库吗，网盘那个地址打不开了，网上也并没有找到别人的，或者可以发我一份吗？邮箱852013212@qq.com，3Q！

**Comment by lvcode** [comment]
/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate 可以发我一份吗？邮箱l8q9@163.com

**Comment by February12** [comment]
/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate 可以发我一份吗？邮箱18075375969@163.com    谢谢

**Comment by u2gign** [comment]
/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate 可以发我一份吗？邮箱47480071@qq.com 谢谢

**Comment by Bofearless** [comment]
@wskiwhexing 请问能把作者发你的那个动态库发一下嘛？谢谢。 bofearless@gmail.com

**Comment by Zhulmin** [comment]
libsubstrate.dylib 的网盘地址失效,请问能发一份到我邮箱吗 zhulmin1458@gmail.com    谢谢

**Comment by Zhulmin** [comment]
> @wskiwhexing 请问能把作者发你的那个动态库发一下嘛？谢谢。 [bofearless@gmail.com](mailto:bofearless@gmail.com)

https://pan.baidu.com/s/1o8PPVGu

**Comment by February12** [comment]
当时好像在网上下载的。具体地址不记得了




| |
朱云龙
|
|
邮箱：18075375969@163.com
|

签名由 网易邮箱大师 定制

在2018年12月04日 14:02，Ra_Hulmin 写道：

@wskiwhexing 请问能把作者发你的那个动态库发一下嘛？谢谢。 bofearless@gmail.com

https://pan.baidu.com/s/1o8PPVGu

**Comment by February12** [comment]
额，文件夹还在，加我QQ，我发给你   845369698




| |
朱云龙
|
|
邮箱：18075375969@163.com
|

签名由 网易邮箱大师 定制

在2018年12月04日 16:16，February12ᵈᵉᵛ 写道：
当时好像在网上下载的。具体地址不记得了




| |
朱云龙
|
|
邮箱：18075375969@163.com
|

签名由 网易邮箱大师 定制

在2018年12月04日 14:02，Ra_Hulmin 写道：

@wskiwhexing 请问能把作者发你的那个动态库发一下嘛？谢谢。 bofearless@gmail.com

https://pan.baidu.com/s/1o8PPVGu

**Comment by haheha** [comment]
> 我按照步骤全部弄好了，也可以弄出ipa 能正常安装，但是要闪退。纠结啦。。 手机不想越狱。。 我在网上下的libsubstrate.dylib 文件。。 不知道是不是这个文件的问题

老铁 方便留个qq吗，请教一下怎么搞得，我手机也没越狱，但是
➜  ~ scp root@192.168.1.248:/usr/lib/libsubstrate.dylib ~/Desktop                    
ssh: connect to host 192.168.1.248 port 22: Connection refused
卡在这里了
