### ISSUE TITLE
新版本微信中遇到问题

### ISSUE THREAD

**Issue by ljfuyuan** [buginux/WeChatRedEnvelop#38]
新版本微信中打包IPA后，安装提示
This app contains a WatchKit app with an invalid bundle identifier. The bundle identifier of a WatchKit app must have a prefix consisting of the companion app's bundle identifier, followed by a '.'.
在重签名的软件中，貌似没有设置watchapp id的方式，有什么解决办法么？

新年快乐。

**Comment by buginux** [comment]
可以直接在原来的 WeChat.app 当中把 Watch 这个目录删除，这个目录是手表应用的，跟普通应用无关。删除就可以了。

**Comment by ljfuyuan** [comment]
我之前尝试过了，删除了Watch目录，可以安装，但是会闪退，我怀疑过是不是我的lib没有处理好，但是即使用原装的微信，删除Watch目录后打包，一样闪退

**Comment by ljfuyuan** [comment]
能否帮忙提供一个微信的砸壳后的裸包，我测试下是不是pp助手下载的包不对，我这边手机升级到10.2了，没办法砸。

**Comment by buginux** [comment]
确认下路径修改是否正确，是不是跟文章上的一致。同时确保有把两个dylib都拷贝到 wechat.app 目录下。

**Comment by ljfuyuan** [comment]
确定的 不知道是不是因为我是从pp助手上直接下载的wechat 我是用的6.5.2的版本 系统是iOS10.1

**Comment by buginux** [comment]
https://github.com/buginux/WeChatRedEnvelop/issues/35

看下你是否有遇到这个问题，如果还是有问题，我们再具体讨论。

**Comment by ljfuyuan** [comment]
谢谢，我参考了#35的方法，确实发现libsubstrate不一致，然后下载放进去后，依然闪退，WeChatRedEnvelop.dylib是直接用你的代码build的，还发现一个奇怪的问题，安装到手机上后，我之前的正版微信会无法连接网络，我删除修改版的微信后，他就可以连接网络了，期间我关闭正版微信再开修改过的依然闪退。不知道哪步出了问题

**Comment by ljfuyuan** [comment]
已解决，下载了PP助手的越狱版，下载正版会出这个问题

**Comment by buginux** [comment]
👍
