### ISSUE TITLE
BigBoss上搜不到WeChatRedEnvelop

### ISSUE THREAD

**Issue by douniwan5788** [buginux/WeChatRedEnvelop#40]
RT

**Comment by buginux** [comment]
我刚刚试了下是没有问题的，而且从下载量来看应该是可以搜索到的。请确认下你是否添加了 BigBoss 的源，然后看看你的搜索输入有没有错误。

**Comment by douniwan5788** [comment]
确实搜不到 ipad mini ios 7.1.2 不知道是不是太老了，自己编译是可以的
http://p1.bpimg.com/4851/bdb98a430e8efef8.jpg
http://p1.bpimg.com/4851/7026e0f5cefea0cb.jpg
