### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ifgyong** [buginux/WeChatRedEnvelop#42]
`Makefile:6: theos/makefiles/common.mk: No such file or directory
Makefile:12: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.`
报这个错 怎么搞？

**Comment by Zxxxx** [comment]
这个作者之前回复了
在命令行中输入 export theos=/opt/theos

**Comment by buginux** [comment]
请参考[这个issue](https://github.com/buginux/WeChatRedEnvelop/issues/33)
