### ISSUE TITLE
App installation failed

### ISSUE THREAD

**Issue by ifgyong** [buginux/WeChatRedEnvelop#44]
这个是用Xcode安装的时候出现的`A WatchKit app within this app is not a valid bundle.`，我该怎么办呢

**Comment by buginux** [comment]
把 WeChat.app 里面的 Watch 目录删除。

**Comment by ifgyong** [comment]
我删除过了 Watch目录,在越狱的手机上系统是9.3.2可以装上，但是我的手机是 10.2系统，报错了。提示‘This application is not built for this device.’

**Comment by buginux** [comment]
应该是签名问题，确认下是否正确签名了。
