### ISSUE TITLE
scp root@<your.device.ip>:/usr/lib/libsubstrate.dylib ~/Desktop

### ISSUE THREAD

**Issue by rikyou215** [buginux/WeChatRedEnvelop#46]
执行这个的时候提示 ssh: connect to host 192.168.0.111 port 22: Connection refused，这个我的手机改怎么设置，需要安装什么？希望大神给我解答下。

**Comment by buginux** [comment]
参考下[这篇文章](http://www.swiftyper.com/2016/01/25/ios-tweak-install-guide/)，你应该连环境都还没搭好。

**Comment by rikyou215** [comment]
这个必须对设备进行越狱吗？

**Comment by buginux** [comment]
是的，不越狱是没办法安装 ssh 的。

**Comment by rikyou215** [comment]
好的，非诚感谢你耐心的解答

**Comment by buginux** [comment]
链接: https://pan.baidu.com/s/1mh7vCJu 密码: 6piq
