### ISSUE TITLE
输入 make 报错

### ISSUE THREAD

**Issue by Smmw** [buginux/WeChatRedEnvelop#50]
这是错误
Makefile:6: theos/makefiles/common.mk: No such file or directory
Makefile:12: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.
然后输入
EXPORT THEOS=/opt/theos
这个实在terminal 输入吗？，。。
报错
-bash: EXPORT: command not found

**Comment by buginux** [comment]
是 `export THEOS=/opt/theos`，这个是大小写敏感的。

**Comment by Smmw** [comment]
还有git clone --recursive https://github.com/alexzielenski/optool.git
报错
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:beelsebob/CoreParse.git' into submodule path '/Users/Yiming/GitHub/optool/optool/FSArgumentParser/CoreParse' failed
Failed to clone 'CoreParse'. Retry scheduled
Cloning into '/Users/Yiming/GitHub/optool/optool/FSArgumentParser/CoreParse'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:beelsebob/CoreParse.git' into submodule path '/Users/Yiming/GitHub/optool/optool/FSArgumentParser/CoreParse' failed
Failed to clone 'CoreParse' a second time, aborting
Failed to recurse into submodule path 'optool/FSArgumentParser'

**Comment by Smmw** [comment]
还有 
Ditto:WeChatRedEnvelop Yiming$ export THEOS=/opt/theos
Ditto:WeChatRedEnvelop Yiming$ make
Makefile:6: theos/makefiles/common.mk: No such file or directory
Makefile:12: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.

**Comment by Smmw** [comment]
是不是要安装theos？

**Comment by buginux** [comment]
theos 是基础环境，你都没装当然是会出问题。还有那个 clone 的问题，这个是你那边的问题，我没办法帮你解决啊。你自己稍微再看看吧。

**Comment by Smmw** [comment]
谢谢 我再研究研究！

**Comment by Smmw** [comment]
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
==> Error: You do not have an SDK in /Library/Developer/CommandLineTools/Platforms/iPhoneOS.platform/Developer/SDKs.
我下载了 xcode 从那里拷过来 platform 放进去 然后make  报错
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
> Making all for tweak WeChatRedEnvelop…
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (armv7)…
xcrun: error: SDK "iphoneos" cannot be located
==> Compiling XGPayingViewController.m (armv7)…
xcrun: error: SDK "iphoneos" cannot be located
==> Linking tweak WeChatRedEnvelop (armv7)…
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
xcrun: error: SDK "iphoneos" cannot be located
==> Compiling XGPayingViewController.m (arm64)…
xcrun: error: SDK "iphoneos" cannot be located
==> Linking tweak WeChatRedEnvelop (arm64)…
xcrun: error: SDK "iphoneos" cannot be located
==> Merging tweak WeChatRedEnvelop…
==> Signing WeChatRedEnvelop…

**Comment by Smmw** [comment]
这是配置好的theos
Ditto:opt Yiming$ nic.pl
NIC 2.0 - New Instance Creator
------------------------------
  [1.] iphone/activator_event
  [2.] iphone/application_modern
  [3.] iphone/cydget
  [4.] iphone/flipswitch_switch
  [5.] iphone/framework
  [6.] iphone/ios7_notification_center_widget
  [7.] iphone/library
  [8.] iphone/notification_center_widget
  [9.] iphone/preference_bundle_modern
  [10.] iphone/tool
  [11.] iphone/tweak
  [12.] iphone/xpc_service

**Comment by buginux** [comment]
不用拷什么啊，只要装了 Xcode 就行了。我没碰到过你这个错误，实在不知道它是怎么产生的。

**Comment by Smmw** [comment]
我安装了xcode之后 make 就提示我
Error: You do not have an SDK in /Library/Developer/CommandLineTools/Platforms/iPhoneOS.platform/Developer/SDKs.
我从xcode里考进去之后make 虽然有错 但是有 .dylib文件用 otool -L WeChatRedEnvelop.dylib 打开发现是/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate 按照你的答案 把它考出来 改名字 发现 这个路径下面没有CydiaSubstrate.framework/CydiaSubstrate。

**Comment by Smmw** [comment]
我如果不考进去 那个CommandLineTools 里没有 Platforms/iPhoneOS.platform/Developer/SDKs.

**Comment by Smmw** [comment]
我重新下载一下xcode 看看有没有那个platforms

**Comment by Smmw** [comment]
>>>help usb
usb 	ssh device over usb(Max OS X support only).
	args: [username] [password] [port]
	example: 'usb root alpine' or 'usb root alpine 2222'
在吗  这个username 和 password 是什么意思？那里的 username和password？我百度和google都查了 查不到啊。？

**Comment by Smmw** [comment]
错误解决了  缺这一行 code
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
