### ISSUE TITLE
能不能把你砸壳后的文件文件发上来,我自己用xcode装到我的手机上

### ISSUE THREAD

**Issue by Gx952743985** [buginux/WeChatRedEnvelop#51]
看你发的步骤太麻了,能不能给我一份,我用自己证书签名

**Comment by Gx952743985** [comment]
参考文章

移动App入侵与逆向破解技术－iOS篇5
DingTalkNoJailTweak
原谅我太笨,我只找到这两个,并没有找到微信的工程包.

**Comment by fujinlin** [comment]
哪有网盘地址呀 ，求发一个
