### ISSUE TITLE
安装好了 微信里找不到这个插件啊

### ISSUE THREAD

**Issue by Smmw** [buginux/WeChatRedEnvelop#52]
我删除了 watch 因为安装的时候报错 说 watchkit is not vaild 然后签名 安装 成功了  但是找不到那个插件啊

**Comment by Smmw** [comment]
我用的是你砸壳过的。我应该是没有 把那个文件添加进去。。

**Comment by renzifeng** [comment]
我也是用的砸壳过的，安装上没有插件，请问你是怎么解决的

**Comment by Smmw** [comment]
你要用 optool 把插件注入进去
这一步$ /path/to/optool install -c load -p "@executable_path/WeChatRedEnvelop.dylib" -t wechat/Payload/WeChat.app/WeChat 
注入成功会有提示的

**Comment by renzifeng** [comment]
这一步我不太明白  能否发个qq交流一下

**Comment by Smmw** [comment]
784718278
