### ISSUE TITLE
执行 xcodebuild -project optool.xcodeproj -configuration Release ARCHS="i386 x86_64" build 报错

### ISSUE THREAD

**Issue by Smmw** [buginux/WeChatRedEnvelop#53]
报错
/Users/Yiming/GitHub/optool/optool/FSArgumentParser/CoreParse/CoreParse/Parsers/CPShiftReduceParsers/CPItem.m:20:13: error: 
      synthesized property 'rule' must either be named the same as a compatible instance variable or
      must explicitly name an instance variable
@synthesize rule;
            ^
/Users/Yiming/GitHub/optool/optool/FSArgumentParser/CoreParse/CoreParse/Parsers/CPShiftReduceParsers/CPItem.m:21:13: error: 
      synthesized property 'position' must either be named the same as a compatible instance
      variable or must explicitly name an instance variable
@synthesize position;

这是文件里的代码
@interface CPItem ()

@property (readwrite,retain) CPRule *rule;
@property (readwrite,assign) NSUInteger position;

@end

@implementation CPItem

@synthesize rule;
@synthesize position;
这个报错是什么意思说啊？

**Comment by Smmw** [comment]
inconsistent number of instance variables specified
    NSMutableDictionary **table;
这意思 是不是 我缺少这个库？

**Comment by buginux** [comment]
首先确认下你库有没有下全，这个库是有依赖的。

另外看看编译参数有没有错误，再就是编译环境。

**Comment by Smmw** [comment]
我的错误 跟他的错误一样
https://github.com/buginux/WeChatRedEnvelop/issues/55
我去掉 了i386
xcodebuild -project optool.xcodeproj -configuration Release ARCHS="x86_64" build
然后报错
Check dependencies
error: There is no SDK with the name or path '/Users/Yiming/GitHub/optool/macosx10.9'

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Comment by Smmw** [comment]
你说的编译环境都需要什么？我安装xcode theos 还有commendline tool

**Comment by Smmw** [comment]
删除i368 不报错  已解决！

**Comment by sxgfxm** [comment]
在最新版的mac系统安装optool遇到同样问题，按照此方法http://www.cnblogs.com/yuanxiaoping_21cn_com/p/5532959.html顺利解决，分享给需要的人
