### ISSUE TITLE
微信关闭一段时间后就无法主动推送消息

### ISSUE THREAD

**Issue by maidousj** [buginux/WeChatRedEnvelop#54]
RT，关闭一段时间后就无法主动推送消息，因此也无法自动抢包。请问这个是和苹果的推送机制有关的么？这种自己制作证书的方式无法主动推送？还是我的安装过程有问题。

我是没越狱安装的。

谢谢！

**Comment by buginux** [comment]
首先，推送消息的话，我这边是没有问题的，而且目前为止没有其他人反应。建议你卸载掉原生的 APP，只留下修改过的试试。

另外，非越狱的机子在进入后台时就会被系统休眠的，因此没办法抢是正常的。如果需要要后台也能抢，还是得越狱。

**Comment by maidousj** [comment]
感谢回复！
这个非越狱的机子在进入后台时会被系统休眠是指所有应用么？原版的wechat即使不在后台也可以收到的。

**Comment by buginux** [comment]
是所有应用，这本身就是 iOS 系统的机制。
后台可以接收到是推送消息，与普通的消息路径是不一样的。
