### ISSUE TITLE
没有越狱手机怎么破？

### ISSUE THREAD

**Issue by YJManager** [buginux/WeChatRedEnvelop#57]
RT 能共享一下砸壳的微信包 或者 待签名的包吗？感激涕零

**Comment by buginux** [comment]
去我博客上看吧，我之前有分享过一个，在评论里面。

**Comment by YJManager** [comment]
你的博客没看到评论功能啊

**Comment by buginux** [comment]
有评论啊，你自己再确认下，这我帮不了你了。

**Comment by fujinlin** [comment]
求共享一下砸壳的微信包 或者 待签名的包吗？感激涕零  你的博客没有评论功能啊，。。。。求个砸壳的包
