### ISSUE TITLE
建议增加关键字和特殊群

### ISSUE THREAD

**Issue by real3841** [buginux/WeChatRedEnvelop#59]
to xxx 抢错翻倍
xxx 群是老板群。。不能抢红包之类的功能

**Comment by buginux** [comment]
这个需求实现起来就比较复杂了，目前可能没有时间精力去完成。

**Comment by zhangrongwu** [comment]
这个可以根据消息类型 49（微信红包消息类型）来做判断，类型为49时读取匹配关键字处理

**Comment by buginux** [comment]
已经着手准备开发了

**Comment by buginux** [comment]
已支持最新版本微信，欢迎使用
