### ISSUE TITLE
Undefined symbols for architecture armv7 Error

### ISSUE THREAD

**Issue by wilder-misfit** [buginux/WeChatRedEnvelop#6]
After I run the command, make package install, it shows me that.

Making all for tweak WeChatRedEnvelop...
 Linking tweak WeChatRedEnvelop...
ld: warning: ignoring file ~/WeChatRedEnvelop/theos/lib/libsubstrate.dylib, missing required architecture armv7 in file ~/WeChatRedEnvelop/theos/lib/libsubstrate.dylib (2 slices)
Undefined symbols for architecture armv7:
  "_MSHookMessageEx", referenced from:
      _logosLocalInit() in Tweak.xm.c9db2f61.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [obj/WeChatRedEnvelop.dylib.ba964c90.unsigned] Error 1
make[1]: *** [internal-library-all_] Error 2
make: *** [WeChatRedEnvelop.all.tweak.variables] Error 2

What do you think about this?

**Comment by buginux** [comment]
It seems that there is a problem with your libsubstrate.dylib, maybe your theos do not installed correctly. which instructions do you followed on?

**Comment by wilder-misfit** [comment]
I follow the guide with your document at http://www.swiftyper.com/ios-tweak-install-guide .
What's more, I found that the instruction "sudo chmod 777 /opt/theos/bin/dkpg-deb" should be "sudo chmod 777 /opt/theos/bin/dpkg-deb".
Ok, I found the root cause. It seems that we should copy the file, libsubstrate.dylib, from the ios device to the project directory.

**Comment by buginux** [comment]
Sorry about the typo.

You are correct, you should copy the /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate file from iOS device and paste it into /opt/theos/libsubstrate.dylib on your OS X.

I am not sure can you read Chinese, but I've mentioned it in my tutorial guide.

Anyway, you found the solution yourself, it's great.
