### ISSUE TITLE
iOS 10 报错

### ISSUE THREAD

**Issue by wskiwhexing** [buginux/WeChatRedEnvelop#60]
在iOS 10 的机器上安装不上，提示信息如下：

App installation failed
This app contains a WatchKit app with an invalid bundle identifier. The bundle identifier of a WatchKit app must have a prefix consisting of the companion app's bundle identifier, followed by a '.'.

根据上面的意思是说微信里用了  WatchKit 要设置下这个东西的identifier 但是不知道怎么去修改，请问下大家有没有碰到这样的错误。
但是由于没有编译环境无法修改，请楼主查看一下情况。

**Comment by wskiwhexing** [comment]
已经找到答案

**Comment by fujinlin** [comment]
怎么解决的呀， WeChatRedEnvelop.lib可以发一个给我吗。谢谢 邮箱247841289@qq.com
