### ISSUE TITLE
make 时 报错 没有 substrate.h 文件。

### ISSUE THREAD

**Issue by HuaianWu** [buginux/WeChatRedEnvelop#61]
clone 以后执行 make 操作时 报错 没有 substrate.h 文件。iOSOpenDev 已经装成功。也编译过别的 dylib 。还有就是我的 /usr/lib/ 下没有 libsubstrate.dylib  。/Library/Frameworks/CydiaSubstrate.framework/下 也没有 CydiaSubstrate。
求解答~
thx!

**Comment by HuaianWu** [comment]
theos 环境也装了.

**Comment by buginux** [comment]
你用 theos 编译其它项目没有问题吗。如果是报 substrate.h 的错，我认为应该就是环境的问题。

**Comment by HuaianWu** [comment]
谢谢，还有一个问题 我从 pp助手 下载下来的 ipa 文件 架构是 armv7 x86_64 的 是不是需要我编译的 dylib 的时候 也有 x86_64 的架构。 x86_64 和 arm架构 能一同用 xcode 编译出来吗？

**Comment by buginux** [comment]
iOS 应用都是 ARM 架构的，不会有 X86 的吧。

**Comment by HuaianWu** [comment]
<img width="571" alt="2017-01-13 3 26 59" src="https://cloud.githubusercontent.com/assets/15134353/21921664/c03c5e02-d9a4-11e6-8d77-43182856ac6d.png">
就这样。。

**Comment by buginux** [comment]
theos 编译出来是都有的 32 位，64 位，还有一种是 fat 的，包容两种架构。所以不需要特别指定版本。

**Comment by HuaianWu** [comment]
来报个喜 我成功了。我使用 lipo -remove 命令 把 pp助手 下载下来的预约文件中的 fat file 的 x86_64 架构去除掉了。 然后注入我自己写的代码编译出的 dylib 。安装成功也实现了对应的功能。下面研究我为啥编译你的代码会报错。。。
ps( 我用的命令是 lipo WeChat -remove x86_64 -output WeChat.remove。然后 将 Wechat 文件删除掉 把 WeChat 文件改名)
