### ISSUE TITLE
最新版微信不能自动抢红包

### ISSUE THREAD

**Issue by fq050766** [buginux/WeChatRedEnvelop#62]
从cydia里面直接下载WeChatRedEnvelop插件和重新打包两种方式都没有实现自动抢红包。是最新版微信不行吗？

**Comment by fq050766** [comment]
iOS9.3.3,已越狱，可以看到设置界面的自动抢红包开关，但是不能自动抢

**Comment by buginux** [comment]
这个只能抢群组里的红包，请确认你是不是在群组里的。私聊是不管用的。

**Comment by fq050766** [comment]
@buginux 好的，群组里面可以抢了，但是有个问题就是在非越狱机器上面安装的时候  xCode上面 提示 `A valid provisioning profile for this executable was not found.`
有遇到过的吗？

**Comment by fq050766** [comment]
傻逼了，选错证书了。已经解决了，谢谢！
