### ISSUE TITLE
微信点设置之后app崩溃

### ISSUE THREAD

**Issue by HugoChanD** [buginux/WeChatRedEnvelop#63]
ios8.4 微信6.3.15 os x 10.12 正常签名安装app 进微信之后点设置app崩溃退出 其它系统功能正常

**Comment by buginux** [comment]
估计是版本太低，代码改了吧，建议升级一下微信。

**Comment by buginux** [comment]
可以参考下这个 https://github.com/buginux/WeChatRedEnvelop/issues/67
