### ISSUE TITLE
最后一步optool出错

### ISSUE THREAD

**Issue by fightingForYou** [buginux/WeChatRedEnvelop#65]
➜  Desktop /path/to/optool install -c load -p "@executable_path/WeChatRedEnvelop.dylib" -t wechat/Payload/WeChat.app/WeChat
zsh: no such file or directory: /path/to/optool

**Comment by HugoChanD** [comment]
编译安装optool的路径

**Comment by fightingForYou** [comment]
@HugoChanD  已经解决了 不过微信反作弊做的挺好的 我一用他就强制我下线了 不知道作者能做下防护吗
