### ISSUE TITLE
免越狱的插件在哪里直接能下载啊？

### ISSUE THREAD

**Issue by yisake** [buginux/WeChatRedEnvelop#66]
如题

**Comment by buginux** [comment]
没有直接下载的，都是根据文章手动做的。

**Comment by buginux** [comment]
链接: https://pan.baidu.com/s/1nvrv62H 密码: 84db

**Comment by Lobster-King** [comment]
问下 网盘里面的是砸壳后的么？还是说都做好了 就只剩签名了？

**Comment by Lobster-King** [comment]
我重签名 之后 在设置里面没有看到开关。

**Comment by yisake** [comment]
@Lobster-King 能分享一下吗？我不是dev，没有mac，帮我分享一个签好的ipa？多谢

**Comment by liberize** [comment]
@buginux 这个包可能不对，我重签名以后，设置里面也没有看到开关
能不能重新发一个版本？6.5.2 / 6.5.3 都可以
因为 5s 手机升级了 10.1 越狱不了，只能做一回伸手党了
祝新年快乐！

**Comment by Lobster-King** [comment]
按照文章步骤做一遍，那个包只是给你砸了科，你需要改了执行路径后，注入到微信可执行程序里，然后再重签名。


发自网易邮箱大师
在2017年01月24日 20:16，Paul Lee 写道：

@buginux 这个包可能不对，我重签名以后，设置里面也没有看到开关
能不能重新发一个版本？6.5.2 / 6.5.3 都可以
因为 5s 手机升级了 10.1 越狱不了，只能做一回伸手党了
祝新年快乐！

**Comment by liberize** [comment]
没有越狱手机没办法搞吧


Lobster-King <notifications@github.com>于2017年1月24日 周二21:23写道：

**Comment by Lobster-King** [comment]
有越狱手机就不用这么麻烦了，非越狱机得把dylib注入到可执行文件load commands才会链接到hook程序。发自网易邮箱大师
            在2017年01月24日 21:25，Paul Lee 写道： 没有越狱手机没办法搞吧





Lobster-King <notifications@github.com>于2017年1月24日 周二21:23写道：

**Comment by liberize** [comment]
用 PP 助手里面的 6.5.4 版本，加上作者提供的 libsubstrate.dylib 终于成功了
