### ISSUE TITLE
进入设置界面闪退

### ISSUE THREAD

**Issue by sxgfxm** [buginux/WeChatRedEnvelop#67]
首先非常感谢您提供的解决方案，已成功安装运行。
初始状态下无法自动抢红包，尝试进入设置界面时闪退，想请教一下可能出现什么问题吗？
十分感谢

**Comment by buginux** [comment]
有可能是微信版本问题，照理来说用最新版的应该没有问题，因为我今天才重新打过包，是可能正常使用的。确认下是不是因为版本太旧导致代码不一致的问题。

**Comment by saxon17** [comment]
我刚刚也出现了闪退  我更新下微信试试 （已经越狱IOS 版本 9.3）

**Comment by saxon17** [comment]
更新微信之后解决，但是ipad重启之后  按钮 推不上  （插件生效，但是按钮打不开）

**Comment by sxgfxm** [comment]
我用的微信版本为6.3.1
手机为iPhone6
系统版本为10.2
我尝试用更新版的微信试试吧

**Comment by sxgfxm** [comment]
@buginux 更新越狱版微信至最新版本，问题已经解决，十分感谢。
测试了一下，刚抢到红包就被系统检测到强制下线了……
看来还得继续跟微信开发者斗智斗勇

**Comment by buginux** [comment]
@sxgfxm 我还没碰到这个问题，不知道是不是年末了，微信那边严打了。看运气吧，哈哈。

**Comment by zhangrongwu** [comment]
WeChatRedEnvelop.lib可以发一个给我吗。谢谢 邮箱zhangrongwuios@icloud.com

**Comment by sxgfxm** [comment]
已发送

**Comment by fujinlin** [comment]
WeChatRedEnvelop.lib可以发一个给我吗。谢谢 邮箱247841289@qq.com
