### ISSUE TITLE
WeChatRedEnvelop 下载后无法生成lib

### ISSUE THREAD

**Issue by zhangrongwu** [buginux/WeChatRedEnvelop#69]
zhangrongwudeMacBook-Pro-3:WeChatRedEnvelop zhangrongwu$ make
Makefile:6: theos/makefiles/common.mk: No such file or directory
Makefile:12: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.

发送邮件没有回复，有没有WeChatRedEnvelop.lib呢，直接发一个试试水可以吗

**Comment by buginux** [comment]
命令行输入 `export THEOS=/opt/theos`，这种问题已经很多人问过了，google 一下也有的。

**Comment by zhangrongwu** [comment]
zhangrongwudeMacBook-Pro-3:WeChatRedEnvelop zhangrongwu$ export THEOS=/opt/theos
zhangrongwudeMacBook-Pro-3:WeChatRedEnvelop zhangrongwu$ make
Makefile:6: theos/makefiles/common.mk: No such file or directory
Makefile:12: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.
zhangrongwudeMacBook-Pro-3:WeChatRedEnvelop zhangrongwu$ 






嗯，试过，没用。

**Comment by sxgfxm** [comment]
你查看下你安装theos时设置的IP和端口号是否和makefile中一致，调整为一致再试试。
THEOS_DEVICE_IP = localhost
THEOS_DEVICE_PORT = 2222

**Comment by zhangrongwu** [comment]
😭，先发我一个lib呗，我先注入试试。zhangrongwuios@icloud.com,谢谢啦

**Comment by sxgfxm** [comment]
已经发过了啊  你没收到吗

**Comment by zhangrongwu** [comment]
有有，谢谢，我先注入试试水

**Comment by zhangrongwu** [comment]
Reason: Incompatible library version: WeChat requires version 1.0.0 or later, but WeChatRedEnvelop.dylib provides version 0.0.0
  Dyld Version: 353.12



注入之后看程序闪退log，lib不对吗

**Comment by zhangrongwu** [comment]
lib 生成可以了，就是还会闪退，之前是theos没安装好。

**Comment by buginux** [comment]
闪退一般就是注入没成功，要么就是微信版本过低的原因。

**Comment by zhangrongwu** [comment]
微信版本6.5.3，不知道是不是下载的越狱版本问题。你们有砸过壳的ipa包吗，

**Comment by zhangrongwu** [comment]
注入是用IPAFine的

**Comment by zhangrongwu** [comment]
可以了作者，谢谢
