### ISSUE TITLE
怎么判断WeChatRedEnvelop.dylib是否成功注入？

### ISSUE THREAD

**Issue by NBaby** [buginux/WeChatRedEnvelop#70]
optool我安装不了，改用insert_dylib ，请问怎么判断成功注入了？我运行了重签名微信发现设置里面并没有显示自动抢红包，是微信修复了么还是我没注入成功，微信越狱版本6.5.3

**Comment by sxgfxm** [comment]
建议还是使用optool注入，我之前用yololib注入也不成功，改用optool就好了

**Comment by NBaby** [comment]
能发我一份optool项目文件么，xsz88287703@126.com，谢谢。。我搞optool好久了，昨天弄了一整天放弃了。还有确定现在能用么？我在PP助手下载的越狱版微信惊奇得发现里面已经有你的WeChatRedEnvelop.dylib他们是不是已经用了你的插件，但是设置里面没有。也许要换个砸壳的。

**Comment by lijianfeigeek** [comment]
@NBaby 可以用MachOView，看下 `Load Commands`段，有没有作者的动态库，就可以确定是否注入成功
<img width="332" alt="qq20170125-0 2x" src="https://cloud.githubusercontent.com/assets/7412609/22283611/24ca88da-e31e-11e6-8d7e-6fe5cec3dfdc.png">
。

**Comment by lijianfeigeek** [comment]
@NBaby 用MachOView工具，注入后在微信的二进制文件中能看见，`Load Commands`中能看见动态库。我也用的insert_dylib，yololib没有权限，optool编译不过。不过我重签名安装在未越狱的手机闪退，可能是我用的微信最新版的原因。
<img width="403" alt="qq20170125-0 2x" src="https://cloud.githubusercontent.com/assets/7412609/22284479/7d14225e-e322-11e6-980b-391d3e9cf74d.png">

**Comment by buginux** [comment]
现在解决了吗？

**Comment by NBaby** [comment]
用了网友发的optool注入就好了
