### ISSUE TITLE
走了一遍教程，安装后能看到多出来的选项，但是并没有自动抢红包，是什么原因？

### ISSUE THREAD

**Issue by HePingLaoSan** [buginux/WeChatRedEnvelop#71]
是不是注入没有成功？另外我打包的过程和教程不一样，我是直接将app文件拖到了itunes上导出的ipa，不知道和这个有没有关系

**Comment by buginux** [comment]
请确保你是在群聊里面，私聊红包是不会自动抢的。

**Comment by WWLJ** [comment]
我的按照教程,打出来的ipa,也是没有效果的,而且微信直接提示我使用插件,强制下线了

**Comment by buginux** [comment]
被强制下线说明插件是安装成功的，只是被微信检测出来了。具体微信是怎么检测的还在研究中。

**Comment by WWLJ** [comment]
好的  我也看看

**Comment by WWLJ** [comment]
谢谢

**Comment by HePingLaoSan** [comment]
是的 我在群里测试的时候也收到微信的提示了，当时我的自动延时是1秒

**Comment by zhangrongwu** [comment]
现在还有人吗，能不能发对应的两个.dylib给我。我这不知道初什么错误了，错误信息：无法加载.dylib库

**Comment by zhangrongwu** [comment]
zhangrongwuios@icloud.com

**Comment by dawangjiaowolaixunshan** [comment]
这个检测有头绪了么  ... 怎么检测出来的...记得刚刚开始的时候就算检测出来了..也是可以抢的..
后来自己写了个自己登录的tweak ... 再后来 就不能抢了.. .

**Comment by zhangrongwu** [comment]
快快，看看什么问题监测出来的。我这老是被强制下线，

**Comment by zhangrongwu** [comment]
在代码中添加几个alert不提示，你们怎么进行调试的，我这是修改了，生成->打包->登录，好麻烦

**Comment by raochuan** [comment]
注入成功
Inserting a LC_LOAD_DYLIB command for architecture: arm
Successfully inserted a LC_LOAD_DYLIB command for arm
Inserting a LC_LOAD_DYLIB command for architecture: arm64
Successfully inserted a LC_LOAD_DYLIB command for arm64

但是没有对应的功能

**Comment by buginux** [comment]
强制下线功能是最新版微信加了检测功能，暂时还没找到解决办法。

**Comment by buginux** [comment]
已经解决强制下线问题，请更新代码到最新版本。
