### ISSUE TITLE
微信闪退

### ISSUE THREAD

**Issue by UESTC-LXY** [buginux/WeChatRedEnvelop#72]
版本 6.5.3
手机 6sp 10.2系统

**Comment by UESTC-LXY** [comment]
能不能发一份你签名完的有抢红包功能的ipa 我重新签名一下

**Comment by buginux** [comment]
闪退很大原因是你注入有问题。

**Comment by buginux** [comment]
链接: https://pan.baidu.com/s/1nvrv62H 密码: 84db
