### ISSUE TITLE
插件不起作用,且微信强制下线

### ISSUE THREAD

**Issue by WWLJ** [buginux/WeChatRedEnvelop#73]
我按照教程一步一步来的 ,只不过 微信下的是pp助手里面的越狱版
插件的设置,显示,但是不起作用,然后微信直接强制下线,
提示  系统检测你正在使用红包辅助插件
mac 和 iPhone 版本都是最新的  微信也是最新版

**Comment by buginux** [comment]
被强制下线说明插件是安装成功的，只是被微信检测出来了。具体微信是怎么检测的还在研究中。

**Comment by WWLJ** [comment]
谢谢
