### ISSUE TITLE
消息不会推送, 已经卸载原版微信

### ISSUE THREAD

**Issue by sinceow** [buginux/WeChatRedEnvelop#75]
已经卸载原版微信, 但只要锁屏了就不会推送, 我的 5s 和 6s Plus 都有这样的问题

**Comment by buginux** [comment]
不太确定原因，你去看设置里面看开了没有。我这边是没有问题的。

**Comment by sxyclint** [comment]
越狱还是非越狱？非越狱不推送很正常。当你锁屏，App被挂起，App的签名已经替换成你自己的，Push Notification的证书是微信的，肯定无法推送啊。最简单的解决办法，使用 AVAudioSession 自己写一个后台播放无声音音乐，然后循环让微信常驻在后台，这样即使锁屏还是后台都可以正常接收消息，并触发插件去抢

**Comment by billylai** [comment]
AVAudioSession如何让微信常驻后台？

**Comment by buginux** [comment]
感觉做到常驻后台有点小题大做了，毕竟抢红包也就过节的时候比较集中而已，这里只要开着就好了，或者用 pad 同时开着就行了，手机爱干嘛干嘛。我觉得再去搞个常驻后台性价比不高。
