### ISSUE TITLE
weChat 6.5.3 装完闪退。提示注入成功。

### ISSUE THREAD

**Issue by raochuan** [buginux/WeChatRedEnvelop#77]
weChat 6.5.3 装完闪退。提示注入成功。 
导出错误信息是

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000000e7ffdefe
Triggered by Thread:  0

Dyld Error Message:
  Library not loaded: @executable_path/WeChatRedEnvelop.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/44C624EF-7E87-4D47-A4F5-BC77E13D2BD8/WeChat.app/WeChat
  Reason: no suitable image found.  Did find:
     /private/var/mobile/Containers/Bundle/Application/44C624EF-7E87-4D47-A4F5-BC77E13D2BD8/WeChat.app/WeChatRedEnvelop.dylib: mach-o, but wrong architecture
     /private/var/mobile/Containers/Bundle/Application/44C624EF-7E87-4D47-A4F5-BC77E13D2BD8/WeChat.app/WeChatRedEnvelop.dylib: mach-o, but wrong architecture
  Dyld Version: 353.6

**Comment by zhangrongwu** [comment]
这个好像和另一个dylib有关，你提取后名字没改还是什么。https://pan.baidu.com/share/link?shareid=3104653426&uk=1225320742        efvy

**Comment by raochuan** [comment]
我闪退应该是少检查了依赖问题。
不过我检查依赖没有 /usr/lib/libsubstrate.dylib (compatibility version 0.0.0, current version 0.0.0)
是怎么回事

otool -L WeChatRedEnvelop.dylib
WeChatRedEnvelop.dylib:
	/usr/lib/libautoGetRedEnv.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.13.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.6.21)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1348.22.0)

**Comment by raochuan** [comment]
名字我改了libsubstrate

**Comment by raochuan** [comment]
WeChatRedEnvelop.lib可以发一个给我吗。谢谢 邮箱787717115@qq.com

**Comment by fujinlin** [comment]
WeChatRedEnvelop.lib可以发一个给我吗。谢谢 邮箱247841289@qq.com
