### ISSUE TITLE
微信6.5.3步骤完全正确。设置没有提示？请问是微信强制屏蔽了？

### ISSUE THREAD

**Issue by raochuan** [buginux/WeChatRedEnvelop#78]
yload/WeChat.app/WeChat
Found FAT Header
Found thin header...
Inserting a LC_LOAD_DYLIB command for architecture: arm
Successfully inserted a LC_LOAD_DYLIB command for arm
Writing executable to wechat/Payload/WeChat.app/WeChat...

**Comment by buginux** [comment]
设置没有提示就是注入没有成功，你自己再确认一遍。

**Comment by CainRun** [comment]
你这是怎么安装的? 需要越狱吗?
