### ISSUE TITLE
iOS10无法安装

### ISSUE THREAD

**Issue by zhangrongwu** [buginux/WeChatRedEnvelop#79]
8和9没问题，这是打包有问题吗

**Comment by buginux** [comment]
是打包问题，我自己用的就是 iOS 10，可以安装。

**Comment by zhangrongwu** [comment]
IOS 10 必须要archive 过的应用中提取 embedded.mobileprovision 的文件才能正常安装， 直接选择描述文件在iOS10上无法安装。不知道什么问题。我这安装好了，从archive提取的没问题。

**Comment by zhangrongwu** [comment]
应该是我这发布和开发证书问题
