### ISSUE TITLE
找不到延迟设置的开关

### ISSUE THREAD

**Issue by wenmingvs** [buginux/WeChatRedEnvelop#8]

**Comment by buginux** [comment]
之前做这个 tweak 的时候是用的公司越狱机器，现在放假在家，我自己的手机还没有越狱，没办法进行测试，所以就暂时没有加上。如果这个功能很有需要的话，我晚些时候会加上去的。:smile:

**Comment by vcarus** [comment]
延迟是个好功能。最好是能设置某个时间段内随机。

**Comment by buginux** [comment]
已经添加延迟抢红包开关，具体细节可参看 README。
