### ISSUE TITLE
咨询个问题，在MAC下编译完成后的DYLIB在哪里？

### ISSUE THREAD

**Issue by lkmvip** [buginux/WeChatRedEnvelop#81]
以前就是在Obj里面，这次编译后在obj里面没找到，那这个dylib在哪里？

**Comment by buginux** [comment]
还是在原来的地方啊

**Comment by lkmvip** [comment]
额，是我这边的问题了，用老的源码也没法编译出dylib了，全程无错，就是没dylib
记得以前不放libsubstrate.dylib会提示错误，现在不放也不会提示错误，不知道是不是这关系。。
