### ISSUE TITLE
开发建议，希望增加抢一个红包后延时指定时间抢下一个红包

### ISSUE THREAD

**Issue by lkmvip** [buginux/WeChatRedEnvelop#83]
程序内置的延时是红包出现后延迟指定时间，但是如果同一时间出现的红包多的话，还是会触发腾讯的限制，我用6.5.2试过，结果被封3天，就是因为1秒抢了3个红包

所以这个抢包后延时指定时间再抢下一个，能不能加上？

**Comment by fujinlin** [comment]
帅哥发个WeChatRedEnvelop.dylib 给我 ，247841289@qq.com

**Comment by buginux** [comment]
已经着手准备开发了

**Comment by buginux** [comment]
功能已经完成！
