### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by dP4ng** [buginux/WeChatRedEnvelop#84]
1。在点击领取个人红包时，会提示“请求不成功”，关闭抢红包功能无效，需关闭抢红包功能，并且重启微信才可以。。。
2。不知道其他人有没遇到我的问题。。消息推送好像存在问题。。微信进入后台，锁屏后，没有消息推送通知。。。

测试环境：
微信版本：6.5.4
未越狱
IOS10.2
iPhone 7 Plus
![wechatimg3](https://cloud.githubusercontent.com/assets/22092518/22280755/cf838fb2-e30d-11e6-9c1c-3e849005fda9.jpeg)

**Comment by buginux** [comment]
请求问题已经解决。
推送是证书问题，这个没办法。
