### ISSUE TITLE
小白提问（关于微信ipa注入）

### ISSUE THREAD

**Issue by feizhenzhuang** [buginux/WeChatRedEnvelop#86]
你好，我最近在研究免越狱版本的微信抢红包，看到你已经提供注入完成后的版本,我能问一下如果有了这个文件后，按照你写的文章该继续哪一步呢？ 谢谢了  :)祝新年快乐
![qq 20170129205528](https://cloud.githubusercontent.com/assets/13115887/22404125/4f707546-e665-11e6-9b5e-f411508b6c03.png)

**Comment by buginux** [comment]
重签名就行了

**Comment by feizhenzhuang** [comment]
您好 ，是不是只需要继续按照您博客的 $打包并重签名 这一步使用ios-app-signer  进行重签名 就可以了吗？  谢谢^-^
![1](https://cloud.githubusercontent.com/assets/13115887/22585348/5468f6d8-ea32-11e6-893c-a3b807759f94.PNG)

**Comment by buginux** [comment]
是的。

2017年2月3日 +0800 PM5:01 kevin Fei <notifications@github.com>，写道：
