### ISSUE TITLE
不知道是不是bug

### ISSUE THREAD

**Issue by lkmvip** [buginux/WeChatRedEnvelop#87]
使用最新版（29号更新的那个）插件后，登陆微信会提示登陆异常，这也就算了。。。

使用中也会造成系统不稳定，比如权限丢失，就是像系统相册，系统联系人，safari都打不开都闪退，和系统权限有关的所有操作都会有问题

我系统是9.3.3越狱

昨天遇到这问题排查老半天，最后才确定是这个插件的原因，实在是看不明白才修改了几行代码就会造成那么大的问题。。。。所以也不知道是不是bug了，毕竟用以前的版本都没发生这情况。。

**Comment by buginux** [comment]
我自己使用没有问题，越狱和非越狱的都正常。没有出现过你这种情况。
