### ISSUE TITLE
不会自动抢红包

### ISSUE THREAD

**Issue by CainRun** [buginux/WeChatRedEnvelop#89]
设备: iPhone 5s / iPad Air2
系统: iOS 10.2.1
网络环境: WiFi / 4G
微信版本: 作者提供的6.5.4

**Comment by CainRun** [comment]
这是啥情况咧? 作者不在吗?

**Comment by buginux** [comment]
你用的是越狱版本吗？是自己编译的还是cydia市场的，如果是非越狱版本请你自己确定步骤是不是正确，我这里是有效果的。

**Comment by CainRun** [comment]
不是的呢, 是你提供的那个网盘里下载的, 我只是自己签了个个人开发证书而已, 我的设备都是没有越狱的, 你提供的那个网盘下载的是越狱版本的吗?

**Comment by buginux** [comment]
那你打开开关了吗，是在群里抢的吗，基本上常见的问题我在 README 还有博客上都有写过了。

**Comment by CainRun** [comment]
打开了, 延迟为默认, 我是在私发的, 不是群里的, 群里的还没验证.....

**Comment by buginux** [comment]
。。我已经在 README 写得很明白了，不支持私聊抢红包。我都已经这么用心写了，你们还这样不明不白的，这不是浪费大家时间吗。

**Comment by CainRun** [comment]
对不起哈, 没看清楚.....但是那个群抢红包的, 指挥在4秒后才能抢, 并不是秒抢的, 这是系统限制还是插件限制?

**Comment by buginux** [comment]
。。这是手动指定的，这位爷，你这就过分了，这种已经不算是问题了吧。设置里面明明白白写了可以设置延迟时间的，你还要我怎样。

**Comment by CainRun** [comment]
不不不, 前面那个问题我是没看清, 我道歉, 真的对不起, 但是这个4秒后才抢包是我自己测试得到的结果, 就算我设置了不延迟, 它也是在4秒后才抢, 设置1秒, 2秒, 3秒都是如此

**Comment by buginux** [comment]
这个我这边是不会的，我自己用的就是这个版本的，照理来说应该不会才对，代码里面写的就是根据设置的时长随机抢的。

**Comment by CainRun** [comment]
那就奇怪了, 我继续试试, 之前的问题对不起哈, 真的没有用心去看, 给你造成麻烦了
