### ISSUE TITLE
重签名成功，安装失败

### ISSUE THREAD

**Issue by jacinzhang** [buginux/WeChatRedEnvelop#91]
签名成功
![resign_success](https://cloud.githubusercontent.com/assets/9859965/22636535/e63e2bb4-ec76-11e6-8a68-b611183e6e36.png)

安装失败
![install_failed](https://cloud.githubusercontent.com/assets/9859965/22636480/8b7f6b48-ec76-11e6-9685-6b3009683d3f.png)

OS: 10.1.1
可以确定设备已添加进mobileprovision

 code sign:
```shell
$ codesign -vv -d WeChat.app
Executable=/Users/XIN/Desktop/new_ipa/Payload/WeChat.app/WeChat
Identifier=cn.whaley.ios.remote
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20200 size=509396 flags=0x0(none) hashes=15911+5 location=embedded
Signature size=4700
Authority=iPhone Developer: Kai Ma (F7H9HJRHDL)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Info.plist entries=55
TeamIdentifier=2N824JT6N9
Sealed Resources version=2 rules=13 files=536
Internal requirements count=1 size=176
```

**Comment by buginux** [comment]
安装失败就是重签名出问题了，这个你得自己去找解决方案，基本上就是证书的问题

**Comment by jacinzhang** [comment]
问下，你用的是生产还是发布的来进行重签名的？

**Comment by jacinzhang** [comment]
@buginux 有个不情之请，希望你能帮我一下。我把我注入后的`WeChat.app`发给你，然后你用的provision profile帮我签名试下，我现在签名几种都试了下，所以我在想是不是我前面有什么问题，如果你的签名可以的话，那我就可以确定就是我的签名问题了

希望你能帮我下，刚入门这个逆向，对这个挺大兴趣的....多谢啦

**Comment by jacinzhang** [comment]
哥们，我知道问题所在了，Clutch砸的壳好像有问题，我从PP助手下载的WeChat.ipa就可以。我自己再试试看看哈，谢谢了哈 👍👍👍
