### ISSUE TITLE
Clutch WeChat success?

### ISSUE THREAD

**Issue by jacinzhang** [buginux/WeChatRedEnvelop#92]
使用clutch砸壳

`clutch -d com.tencent.xin`

```shell
com.tencent.xin contains watchOS 2 compatible application. It's not possible to dump watchOS 2 apps with Clutch 2.0.4 at this moment.
Zipping WeChat.app
ASLR slide: 0x10007c000
Dumping <WeChatShareExtensionNew> (arm64)
Patched cryptid (64bit segment)
Writing new checksum
ASLR slide: 0x100038000
Dumping <WeChat> (arm64)
Patched cryptid (64bit segment)
Zipping WeChatShareExtensionNew.appex
Writing new checksum
DONE: /private/var/mobile/Documents/Dumped/com.tencent.xin-iOS7.0-(Clutch-2.0.4).ipa
```

似乎是成功的，但其实好像是失败的，微信里包含`watchOS 2 compatible application`，并没有成功砸开`watchOS 2 compatible application`，导致后续不能成功安装。

我去PP助手越狱市场下载了微信(不用砸壳的)，然后注入动态库、打包、重签名、安装，是成功的。

我又重新找了个不包含`watchOS 2 compatible application`的`网易公开课`试了一下，可以砸壳、打包、重签名、安装，也是成功的。

所以，我就想问下，作者确定是用最新版`Clutch(2.0.4)`手动砸壳微信的么？？？

**Comment by buginux** [comment]
Clutch 不支持 Extension 的，这个官方里面有讲的，你可以自己手动 Google 一下就有了。

**Comment by Gensun** [comment]
Clutch -d com.tencent.xin
2017-05-11 17:02:34.150 Clutch[1026:9965] command: Dump specified bundleID into .ipa file
com.tencent.xin contains watchOS 2 compatible application. It's not possible to dump watchOS 2 apps with Clutch 2.0.4 at this moment.
Zipping WeChat.app
Swapping architectures..
ASLR slide: 0xf0000
Dumping <WeChatShareExtensionNew> (armv7)
Patched cryptid (32bit segment)
Writing new checksum
ASLR slide: 0x1000d0000
Dumping <WeChatShareExtensionNew> (arm64)
Patched cryptid (64bit segment)
Writing new checksum
Swapping architectures..
ASLR slide: 0xe8000
Dumping <WeChat> (armv7)
Patched cryptid (32bit segment)
Zipping WeChatShareExtensionNew.appex
Writing new checksum
ASLR slide: 0x1000e8000
Dumping <WeChat> (arm64)
Patched cryptid (64bit segment)
Connection to 192.168.2.25 closed by remote host.
Connection to 192.168.2.25 closed.
每次都是重启手机，不知道怎么解决？微信的ipa直接applestore下载的，当前是越狱手机10以上的系统

**Comment by buginux** [comment]
额，这个没有碰到过，看下有没有相同情况的小伙伴。

**Comment by PascoCoder** [comment]
@Gensun 我也是，每次到这都重启。。。最后解决了吗？

**Comment by Gensun** [comment]
@PascoCoder 解决了，我在手机端装了一个终端，在上面操作
