### ISSUE TITLE
cydia中下载的1.2.0版本的插件安装之后，在微信的设置里面看不到抢红包相关的设置

### ISSUE THREAD

**Issue by dstmath** [buginux/WeChatRedEnvelop#94]

**Comment by Wee-W** [comment]
确实..看不见设置。微信654

**Comment by buginux** [comment]
唔，可能是上传的问题，大家先不要下载最新版

**Comment by buginux** [comment]
已经重新上传了，今明两天应该就能看到最新版。这次不知道上传上啥毛病了，抱歉。

**Comment by Wee-W** [comment]
效率dalao.....随时关注....

**Comment by dstmath** [comment]
最新版本的2.9号的在微信里面还是看不到抢红包相关设置

**Comment by Wee-W** [comment]
没问题呀，我更新以后已经好了！能正常抢包，延时也是没有问题的！只是不知道作者有没有发现闪退的问题！不频繁，偶尔出现！没装这个插件的时候，微信是没有问题的！不过不太影响使用，支持作者继续开发！

**Comment by dstmath** [comment]
6ps 10.2的系统为啥还是看不见。。

**Comment by Wee-W** [comment]
这个你需要问下作者了。我是6SP  933，微信654

**Comment by buginux** [comment]
应该是可以了，cydia 上已经更新了。我自己下载试过了，没有问题的。

至于说到的闪退问题，我目前还没有碰到，我春节的时候有大量使用过，没有碰到过闪退的问题，不太清楚你这边的闪退是啥原因。

**Comment by Wee-W** [comment]
闪退问题是我自己的问题，不是插件问题。不好意思😣

**Comment by dstmath** [comment]
1.2.1可以咯
