### ISSUE TITLE
6.5.4 免越狱注入版本已过期

### ISSUE THREAD

**Issue by DingSoung** [buginux/WeChatRedEnvelop#95]
顺带问一下， 你使用企业版账号签名的吗？

**Comment by buginux** [comment]
那个是未签名的包，你需要自己签名。

**Comment by billylai** [comment]
请问Distribution目录下的info.plist里的http://7xqonv.com1.z0.glb.clouddn.com/WeChat.ipa，是在外面买的企业证书吗

**Comment by buginux** [comment]
@billylai 这个 ipa 是很久之前的了，现在应该是不能用的了，建议不要下载了，这个是用企业证书签名的。
