### ISSUE TITLE
建议增加保持后台运行的功能

### ISSUE THREAD

**Issue by DingSoung** [buginux/WeChatRedEnvelop#97]
这样就不会错过红包了😅

**Comment by buginux** [comment]
非越狱系统不支持后台功能，只能手动调为不锁屏模式，而且微信只能在前台。

除非你使用越狱机器。

**Comment by DingSoung** [comment]
@buginux 我大致看了下，还是有一些办法的，不确定是否一定行，咱们这个不用上App Store审核，受限制会少很多

**Comment by tata9898** [comment]
x 宝看了一下 貌似有一些自称可以锁屏后台运行的

**Comment by buginux** [comment]
暂时无法实现，先关闭。
