### ISSUE TITLE
ssh: connect to host 192.168.0.153 port 22: Connection refused

### ISSUE THREAD

**Issue by Hanwp** [buginux/WeChatRedEnvelop#98]
作者你好，
我是按照[这个教程](http://www.swiftyper.com/2016/12/26/wechat-redenvelop-tweak-for-non-jailbroken-iphone/) 来尝试的，但是进行到这一步的时候，提示ssh拒绝访问，请问这是因为手机没有越狱吗，还是其他什么原因？
```
scp Clutch/clutch root@<your.device.ip>:/usr/bin/
```

**Comment by Hanwp** [comment]
@buginux

**Comment by lkmvip** [comment]
当然要越狱，不越狱是没法玩这个的
