### ISSUE TITLE
Clutch在iPad上砸壳后的ipa只能运行在ipad上面

### ISSUE THREAD

**Issue by xly1208** [buginux/WeChatRedEnvelop#99]
Clutch在iPad上砸壳后的ipa只能运行在ipad上面，不能运行在iPhone手机上面。看了一下问，只有arm64的可执行文件。
下面是我砸壳出的WeChat文件
localhost:WeChat.app xly$ file WeChat
WeChat: Mach-O 64-bit executable arm64

下面是你砸出的WeChat文件
localhost:WeChat.app xly$ file WeChat
WeChat: Mach-O universal binary with 2 architectures: [arm_v7: Mach-O executable arm_v7] [arm64]
WeChat (for architecture armv7):	Mach-O executable arm_v7
WeChat (for architecture arm64):	Mach-O 64-bit executable arm64

我想知道你是怎么能在砸壳的时候也把其他架构的也砸出来了，谢谢

**Comment by buginux** [comment]
这应该是跟系统架构有关的，你的可执行文件不是 FAT 类型的。你可以试试从PP助手上下载的。

**Comment by xly1208** [comment]
@buginux 看了一下，的确是。在iPad上的WeChat只有arm的。原始的ipa安装包是两种架构都有的，估计是在安装的时候只安装指定架构的！

还有个疑问就是，手动砸壳的话，这种类型的该如何砸壳呢？怎么才能保证两种架构都有呢？是不是在iPhone上砸壳的就都有了啊？

**Comment by xly1208** [comment]
为啥没有回答呢？版主忙着ing？

**Comment by buginux** [comment]
你看你手机是什么版本咯，现在基本上都是 64 位的了吧。一般来讲，你设备是几位的，砸出来的就是几位的，那些助手类软件上下载的一般会包含两种架构的。

**Comment by xly1208** [comment]
这个我明白。我的主要疑问是怎么能像助手上面这样的，能同时保留两种架构的

**Comment by buginux** [comment]
这个的话，我还不是很清楚，还没有研究过这一块，哈哈。

**Comment by xly1208** [comment]
哈，还有个问题问一下，用thoes怎么hook修改属性的的值呢？试了试getter和setter都不行
谢谢了

**Comment by xly1208** [comment]
哈，解决了
